/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/boyd/Applications/Nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/bloom_bloom.o /Users/boyd/Projects/nimrod-bloom/nimcache/bloom_bloom.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <setjmp.h>

#include <math.h>

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct terrorfork101008 terrorfork101008;
typedef struct ebloomfilter102005 ebloomfilter102005;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell41490 tcell41490;
typedef struct tcellseq41506 tcellseq41506;
typedef struct tgcheap43416 tgcheap43416;
typedef struct tcellset41502 tcellset41502;
typedef struct tpagedesc41498 tpagedesc41498;
typedef struct tmemregion23810 tmemregion23810;
typedef struct tsmallchunk23038 tsmallchunk23038;
typedef struct tllchunk23804 tllchunk23804;
typedef struct tbigchunk23040 tbigchunk23040;
typedef struct tintset23015 tintset23015;
typedef struct ttrunk23011 ttrunk23011;
typedef struct tavlnode23808 tavlnode23808;
typedef struct tgcstat43414 tgcstat43414;
typedef struct TSafePoint TSafePoint;
typedef struct TY102153 TY102153;
typedef struct tbloomfilter102009 tbloomfilter102009;
typedef struct TY10865 TY10865;
typedef struct tbasechunk23036 tbasechunk23036;
typedef struct tfreecell23028 tfreecell23028;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI tmurmurhashes102007[2];
typedef NI TY102033[2];
typedef terrorfork101008* tallerrorrates101010[13];
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  ebloomfilter102005  {
  E_Base Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell41490  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41506  {
NI Len;
NI Cap;
tcell41490** D;
};
struct  tcellset41502  {
NI Counter;
NI Max;
tpagedesc41498* Head;
tpagedesc41498** Data;
};
typedef tsmallchunk23038* TY23822[512];
typedef ttrunk23011* ttrunkbuckets23013[256];
struct  tintset23015  {
ttrunkbuckets23013 Data;
};
struct  tmemregion23810  {
NI Minlargeobj;
NI Maxlargeobj;
TY23822 Freesmallchunks;
tllchunk23804* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk23040* Freechunkslist;
tintset23015 Chunkstarts;
tavlnode23808* Root;
tavlnode23808* Deleted;
tavlnode23808* Last;
tavlnode23808* Freeavlnodes;
};
struct  tgcstat43414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41506 Zct;
tcellseq41506 Decstack;
tcellset41502 Cycleroots;
tcellseq41506 Tempstack;
NI Recgclock;
tmemregion23810 Region;
tgcstat43414 Stat;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (E_Base* e, void* ClEnv);
void* ClEnv;
} TY11826;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY11826 raiseAction;
};
struct  tbloomfilter102009  {
NI Capacity;
NF Errorrate;
NI Khashes;
NI Mbits;
TY102153* Intarray;
NI Nbitsperelem;
NIM_BOOL Usemurmurhash;
};
typedef NimStringDesc* TY102209[4];
typedef NI TY23018[8];
struct  tpagedesc41498  {
tpagedesc41498* Next;
NI Key;
TY23018 Bits;
};
struct  tbasechunk23036  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk23038  {
  tbasechunk23036 Sup;
tsmallchunk23038* Next;
tsmallchunk23038* Prev;
tfreecell23028* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23804  {
NI Size;
NI Acc;
tllchunk23804* Next;
};
struct  tbigchunk23040  {
  tbasechunk23036 Sup;
tbigchunk23040* Next;
tbigchunk23040* Prev;
NI Align;
NF Data;
};
struct  ttrunk23011  {
ttrunk23011* Next;
NI Key;
TY23018 Bits;
};
typedef tavlnode23808* TY23814[2];
struct  tavlnode23808  {
TY23814 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell23028  {
tfreecell23028* Next;
NI Zerofield;
};
struct terrorfork101008 {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct TY102153 {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct TY10865 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, murmurhash_102028)(NimStringDesc* key, NU32 seed, tmurmurhashes102007* Result);
N_NIMCALL(void, MurmurHash3_x64_128)(NCSTRING key, NI len, NU32 seed, NI* outhashes);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, hasha_102040)(NimStringDesc* item, NI maxvalue);
N_NIMCALL(NI, hash_99828)(NimStringDesc* x);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, hashb_102047)(NimStringDesc* item, NI maxvalue);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NI, hashn_102054)(NimStringDesc* item, NI n, NI maxvalue);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, getmovernbitsfork_102062)(NI k, NF targeterror, tallerrorrates101010 probabilitytable);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP237)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell41490*, usrtocell_44843)(void* usr);
static N_INLINE(void, rtladdzct_46402)(tcell41490* c);
N_NOINLINE(void, addzct_44818)(tcellseq41506* s, tcell41490* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(E_Base*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_47227)(tcell41490* c);
static N_INLINE(NIM_BOOL, canbecycleroot_44862)(tcell41490* c);
static N_INLINE(void, rtladdcycleroot_45635)(tcell41490* c);
N_NOINLINE(void, incl_42255)(tcellset41502* s, tcell41490* cell);
static N_INLINE(void, decref_46802)(tcell41490* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(TY102153*, newseq_102148)(NI len_102152);
N_NIMCALL(void, initializebloomfilter_102128)(NI capacity, NF errorrate, NI k, NI forcenbitsperelem, NIM_BOOL usemurmurhash, tbloomfilter102009* Result);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NimStringDesc*, HEX24_102203)(tbloomfilter102009* bf);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, NU8 format, NI precision);
N_NIMCALL(TY102153*, hashmurmur_102214)(tbloomfilter102009* bf, NimStringDesc* item);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(TY102153*, hashnimrod_102271)(tbloomfilter102009* bf, NimStringDesc* item);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_75004, TNimType* mt);
N_NIMCALL(TY102153*, hash_102314)(tbloomfilter102009* bf, NimStringDesc* item);
N_NIMCALL(void, insert_102322)(tbloomfilter102009* bf, NimStringDesc* item);
N_NIMCALL(void, failedassertimpl_80021)(NimStringDesc* msg);
N_NIMCALL(NIM_BOOL, lookup_102427)(tbloomfilter102009* bf, NimStringDesc* item);
N_NIMCALL(TY10865*, newseq_104208)(NI len_104212);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NimStringDesc*, nimBoolToStr)(NIM_BOOL x);
N_NIMCALL(void, randomize_98005)(NI seed);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, random_97979)(NI max);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NF, ntcpuTime)(void);
static N_INLINE(NF, HEX2F_79238)(NI x, NI y);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, parseutilsInit)(void);
N_NOINLINE(void, parseutilsDatInit)(void);
N_NOINLINE(void, strutilsInit)(void);
N_NOINLINE(void, strutilsDatInit)(void);
N_NOINLINE(void, timesInit)(void);
N_NOINLINE(void, timesDatInit)(void);
N_NOINLINE(void, mathInit)(void);
N_NOINLINE(void, mathDatInit)(void);
N_NOINLINE(void, hashesInit)(void);
N_NOINLINE(void, hashesDatInit)(void);
N_NOINLINE(void, probabilitiesInit)(void);
N_NOINLINE(void, probabilitiesDatInit)(void);
N_NOINLINE(void, bloomInit)(void);
N_NOINLINE(void, bloomDatInit)(void);
NIM_CONST TY102033 TMP230 = {0,
0}
;
STRING_LITERAL(TMP232, " b", 2);
STRING_LITERAL(TMP238, "K must be <= 12 if force_n_bits_per_elem is not also specified.", 63);
STRING_LITERAL(TMP240, "Specified value of k and error rate for which is not achievable"
" using less than 4 bytes / element.", 98);
STRING_LITERAL(TMP247, "Bloom filter with $1 capacity, $2 error rate, $3 hash functions"
", and requiring $4 bits per stored element.", 106);
STRING_LITERAL(TMP251, "(len|len|len|len|len)(a) (==|==|==|==|==|==|==|==|==|==|==|==|="
"=|==|==|==|==|==|==|==)\012    L seq modified while iterating over "
"it", 129);
STRING_LITERAL(TMP254, "Testing MurmurHash3 code...", 27);
STRING_LITERAL(TMP255, "int(hash_outputs[0]) == - 3758069500696749310\'i64 ", 50);
STRING_LITERAL(TMP256, "int(hash_outputs[1]) == 6565844092913065241\'i64 ", 48);
STRING_LITERAL(TMP257, "hello", 5);
STRING_LITERAL(TMP258, "hash_outputs2[0] == hash_outputs[0] ", 36);
STRING_LITERAL(TMP259, "hash_outputs2[1] == hash_outputs[1] ", 36);
STRING_LITERAL(TMP260, "hash_outputs3[0] != hash_outputs[0] ", 36);
STRING_LITERAL(TMP261, "hash_outputs3[1] != hash_outputs[1] ", 36);
STRING_LITERAL(TMP262, "bf of TBloomFilter ", 19);
STRING_LITERAL(TMP263, "bf2 of TBloomFilter ", 20);
STRING_LITERAL(TMP264, "Testing insertions and lookups...", 33);
STRING_LITERAL(TMP265, "Test element in BF2?: ", 22);
STRING_LITERAL(TMP266, "testing", 7);
STRING_LITERAL(TMP267, "Inserting element.", 18);
STRING_LITERAL(TMP268, "bf2.lookup(\"testing\") ", 22);
STRING_LITERAL(TMP269, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", 62);
STRING_LITERAL(TMP271, "", 0);
STRING_LITERAL(TMP273, "Took ", 5);
STRING_LITERAL(TMP274, " seconds to insert ", 19);
STRING_LITERAL(TMP275, " items.", 7);
STRING_LITERAL(TMP277, "N false positives (of ", 22);
STRING_LITERAL(TMP278, " lookups): ", 11);
STRING_LITERAL(TMP279, "False positive rate ", 20);
STRING_LITERAL(TMP281, " seconds to lookup ", 19);
STRING_LITERAL(TMP282, "N lookup errors (should be 0): ", 31);
STRING_LITERAL(TMP284, "false ", 6);
STRING_LITERAL(TMP285, "true ", 5);
STRING_LITERAL(TMP286, "get_m_over_n_bits_for_k(k = 2, target_error = 1.000000000000000"
"1e-01) == 6 ", 75);
STRING_LITERAL(TMP287, "get_m_over_n_bits_for_k(k = 7, target_error = 1.000000000000000"
"0e-02) == 10 ", 76);
STRING_LITERAL(TMP288, "get_m_over_n_bits_for_k(k = 7, target_error = 1.000000000000000"
"0e-03) == 16 ", 76);
STRING_LITERAL(TMP289, "bf3.n_bits_per_elem == 11 ", 26);
extern TFrame* frameptr_13238;
extern TNimType NTI2425; /* E_Base */
TNimType NTI102005; /* EBloomFilter */
TNimType NTI102072; /* ref EBloomFilter */
extern tgcheap43416 gch_43444;
extern TSafePoint* exchandler_13239;
extern TNimType NTI2459; /* EInvalidIndex */
extern E_Base* currexception_13241;
extern tallerrorrates101010 kerrors_101013;
TNimType NTI102009; /* TBloomFilter */
extern TNimType NTI106; /* int */
extern TNimType NTI126; /* float */
extern TNimType NTI102153; /* seq[int] */
extern TNimType NTI134; /* bool */
tmurmurhashes102007 hashoutputs_102459;
tmurmurhashes102007 hashoutputs2_102801;
TNimType NTI102007; /* TMurmurHashes */
tmurmurhashes102007 hashoutputs3_103201;
NI nelementstotest_103602;
tbloomfilter102009 bf_103604;
tbloomfilter102009 bf2_103804;
NimStringDesc* samplechars_104202;
TY10865* ktestelements_104204;
TY10865* sampleletters_104205;
NI i_104296;
NI j_104308;
NF starttime_104310;
NF endtime_104311;
NI i_104322;
NI falsepositives_104324;
NI i_104335;
NI j_104347;
NI lookuperrors_104360;
NI i_104371;
tbloomfilter102009 bf3_105204;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13238;
	frameptr_13238 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13238 = (*frameptr_13238).prev;
}

N_NIMCALL(void, murmurhash_102028)(NimStringDesc* key, NU32 seed, tmurmurhashes102007* Result) {
	tmurmurhashes102007 result;
	nimfr("murmur_hash", "bloom.nim")
	nimln(26, "bloom.nim");
	memcpy((void*)result, (NIM_CONST void*)TMP230, sizeof(result));
	nimln(27, "bloom.nim");
	nimln(27, "bloom.nim");
	MurmurHash3_x64_128(key->data, key->Sup.len, seed, result);
	nimln(28, "bloom.nim");
	nimln(28, "bloom.nim");
	memcpy((void*)(*Result), (NIM_CONST void*)result, sizeof((*Result)));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI64)(a % b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hasha_102040)(NimStringDesc* item, NI maxvalue) {
	NI result;
	NI LOC1;
	NI TMP231;
	nimfr("hash_a", "bloom.nim")
	result = 0;
	nimln(31, "bloom.nim");
	nimln(31, "bloom.nim");
	nimln(31, "bloom.nim");
	LOC1 = 0;
	LOC1 = hash_99828(item);
	TMP231 = modInt(LOC1, maxvalue);
	result = (NI64)(TMP231);
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NI, hashb_102047)(NimStringDesc* item, NI maxvalue) {
	NI result;
	NimStringDesc* LOC1;
	NI LOC2;
	NI TMP233;
	nimfr("hash_b", "bloom.nim")
	result = 0;
	nimln(34, "bloom.nim");
	nimln(34, "bloom.nim");
	nimln(34, "bloom.nim");
	nimln(34, "bloom.nim");
	LOC1 = 0;
	LOC1 = rawNewString(item->Sup.len + 2);
appendString(LOC1, item);
appendString(LOC1, ((NimStringDesc*) &TMP232));
	LOC2 = 0;
	LOC2 = hash_99828(LOC1);
	TMP233 = modInt(LOC2, maxvalue);
	result = (NI64)(TMP233);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashn_102054)(NimStringDesc* item, NI n, NI maxvalue) {
	NI result;
	NI LOC1;
	NI LOC2;
	NI TMP234;
	NI TMP235;
	NI TMP236;
	nimfr("hash_n", "bloom.nim")
	result = 0;
	nimln(40, "bloom.nim");
	nimln(40, "bloom.nim");
	nimln(40, "bloom.nim");
	nimln(40, "bloom.nim");
	nimln(40, "bloom.nim");
	LOC1 = 0;
	LOC1 = hasha_102040(item, maxvalue);
	nimln(40, "bloom.nim");
	nimln(40, "bloom.nim");
	LOC2 = 0;
	LOC2 = hashb_102047(item, maxvalue);
	TMP234 = mulInt(n, LOC2);
	TMP235 = addInt(LOC1, (NI64)(TMP234));
	if ((NI64)(TMP235) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
	TMP236 = modInt((NI64)abs((NI64)(TMP235)), maxvalue);
	result = (NI64)(TMP236);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP237)(void* p, NI op) {
	ebloomfilter102005* a;
	a = (ebloomfilter102005*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}

static N_INLINE(tcell41490*, usrtocell_44843)(void* usr) {
	tcell41490* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41490*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41490))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46402)(tcell41490* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44818(&gch_43444.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41490* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44843(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46402(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_13239;
	exchandler_13239 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_13239 = (*exchandler_13239).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_13238 = s;
}

static N_INLINE(E_Base*, getCurrentException)(void) {
	E_Base* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2442, "system.nim");
	result = currexception_13241;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_44862)(tcell41490* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_45635)(tcell41490* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_42255(&gch_43444.Cycleroots, c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_47227)(tcell41490* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_44862(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_45635(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_46802)(tcell41490* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_46402(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_44862(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_45635(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell41490* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_44843(src);
		incref_47227(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell41490* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_44843((*dest));
		decref_46802(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) &currexception_13241, (*currexception_13241).parent);
}

N_NIMCALL(NI, getmovernbitsfork_102062)(NI k, NF targeterror, tallerrorrates101010 probabilitytable) {
	NI result;
	NIM_BOOL searchingformovern;
	NI movern;
	nimfr("get_m_over_n_bits_for_k", "bloom.nim")
	result = 0;
	nimln(44, "bloom.nim");
	{
		ebloomfilter102005* e_102071;
		NimStringDesc* LOC5;
		nimln(44, "bloom.nim");
		if (!(12 < k)) goto LA3;
		e_102071 = 0;
		nimln(1991, "system.nim");
		e_102071 = (ebloomfilter102005*) newObj((&NTI102072), sizeof(ebloomfilter102005));
		(*e_102071).Sup.Sup.m_type = (&NTI102005);
		nimln(1992, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_102071).Sup.message; (*e_102071).Sup.message = copyStringRC1(((NimStringDesc*) &TMP238));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(45, "bloom.nim");
		raiseException((E_Base*)e_102071, "EBloomFilter");
	}
	LA3: ;
	nimln(46, "bloom.nim");
	searchingformovern = NIM_TRUE;
	nimln(47, "bloom.nim");
	movern = 2;
	nimln(48, "bloom.nim");
	while (1) {
		TSafePoint TMP239;
		if (!searchingformovern) goto LA6;
		nimln(49, "bloom.nim");
		pushSafePoint(&TMP239);
		TMP239.status = setjmp(TMP239.context);
		if (TMP239.status == 0) {
			nimln(50, "bloom.nim");
			{
				nimln(50, "bloom.nim");
				if ((NU)(k) > (NU)(12)) raiseIndexError();
				if ((NU)(movern) >= (NU)(probabilitytable[(k)- 0]->Sup.len)) raiseIndexError();
				if (!(probabilitytable[(k)- 0]->data[movern] < targeterror)) goto LA10;
				nimln(51, "bloom.nim");
				searchingformovern = NIM_FALSE;
				nimln(52, "bloom.nim");
				result = movern;
				nimln(53, "bloom.nim");
				popSafePoint();
				goto BeforeRet;
			}
			goto LA8;
			LA10: ;
			{
				nimln(55, "bloom.nim");
				movern = addInt(movern, 1);
			}
			LA8: ;
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&F);
			if (isObj(getCurrentException()->Sup.m_type, (&NTI2459))) {
				ebloomfilter102005* volatile e_102105;
				NimStringDesc* LOC15;
				TMP239.status = 0;
				e_102105 = 0;
				nimln(1991, "system.nim");
				e_102105 = (ebloomfilter102005*) newObj((&NTI102072), sizeof(ebloomfilter102005));
				(*e_102105).Sup.Sup.m_type = (&NTI102005);
				nimln(1992, "system.nim");
				LOC15 = 0;
				LOC15 = (*e_102105).Sup.message; (*e_102105).Sup.message = copyStringRC1(((NimStringDesc*) &TMP240));
				if (LOC15) nimGCunrefNoCycle(LOC15);
				nimln(57, "bloom.nim");
				raiseException((E_Base*)e_102105, "EBloomFilter");
				popCurrentException();
			}
		}
		if (TMP239.status != 0) reraiseException();
	} LA6: ;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, initializebloomfilter_102128)(NI capacity, NF errorrate, NI k, NI forcenbitsperelem, NIM_BOOL usemurmurhash, tbloomfilter102009* Result) {
	NI khashes;
	NF bitsperelem;
	NI nbitsperelem;
	NI mbits;
	NI TMP242;
	NI mints;
	NI TMP243;
	NI TMP244;
	tbloomfilter102009 LOC15;
	nimfr("initialize_bloom_filter", "bloom.nim")
	khashes = 0;
	bitsperelem = 0;
	nbitsperelem = 0;
	nimln(71, "bloom.nim");
	{
		NF LOC5;
		NF LOC6;
		NF LOC7;
		NF LOC8;
		nimln(71, "bloom.nim");
		if (!(k < 1)) goto LA3;
		nimln(72, "bloom.nim");
		nimln(72, "bloom.nim");
		nimln(72, "bloom.nim");
		nimln(72, "bloom.nim");
		LOC5 = 0;
		LOC5 = log(errorrate);
		nimln(72, "bloom.nim");
		nimln(72, "bloom.nim");
		LOC6 = 0;
		LOC6 = log(2.0000000000000000e+00);
		LOC7 = 0;
		LOC7 = pow(LOC6, 2.0000000000000000e+00);
		bitsperelem = ceil(((NF)(-1.0000000000000000e+00) * (NF)(((NF)(LOC5) / (NF)(LOC7)))));
		nimln(73, "bloom.nim");
		nimln(73, "bloom.nim");
		nimln(73, "bloom.nim");
		LOC8 = 0;
		LOC8 = log(2.0000000000000000e+00);
		khashes = lrint(((NF)(LOC8) * (NF)(bitsperelem)));
		nimln(74, "bloom.nim");
		nbitsperelem = lrint(bitsperelem);
	}
	goto LA1;
	LA3: ;
	{
		nimln(76, "bloom.nim");
		{
			nimln(76, "bloom.nim");
			if (!(forcenbitsperelem < 1)) goto LA12;
			nimln(77, "bloom.nim");
			nbitsperelem = getmovernbitsfork_102062(k, errorrate, kerrors_101013);
		}
		goto LA10;
		LA12: ;
		{
			nimln(79, "bloom.nim");
			nbitsperelem = forcenbitsperelem;
		}
		LA10: ;
		nimln(80, "bloom.nim");
		khashes = k;
	}
	LA1: ;
	nimln(82, "bloom.nim");
	nimln(82, "bloom.nim");
	TMP242 = mulInt(capacity, nbitsperelem);
	mbits = (NI64)(TMP242);
	nimln(83, "bloom.nim");
	nimln(83, "bloom.nim");
	nimln(83, "bloom.nim");
	TMP243 = divInt(mbits, 64);
	TMP244 = addInt(1, (NI64)(TMP243));
	mints = (NI64)(TMP244);
	nimln(85, "bloom.nim");
	memset((void*)&LOC15, 0, sizeof(LOC15));
	memset((void*)&LOC15, 0, sizeof(LOC15));
	LOC15.Capacity = capacity;
	LOC15.Errorrate = errorrate;
	LOC15.Khashes = khashes;
	LOC15.Mbits = mbits;
	nimln(87, "bloom.nim");
	LOC15.Intarray = newseq_102148(mints);
	LOC15.Nbitsperelem = nbitsperelem;
	LOC15.Usemurmurhash = usemurmurhash;
	genericShallowAssign((void*)Result, (void*)&LOC15, (&NTI102009));
	popFrame();
}

N_NIMCALL(NimStringDesc*, HEX24_102203)(tbloomfilter102009* bf) {
	NimStringDesc* result;
	TY102209 LOC1;
	nimfr("$", "bloom.nim")
	result = 0;
	nimln(93, "bloom.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	nimln(94, "bloom.nim");
	LOC1[0] = nimIntToStr((*bf).Capacity);
	nimln(94, "bloom.nim");
	LOC1[1] = nsuformatFloat((*bf).Errorrate, ((NU8) 2), 1);
	nimln(94, "bloom.nim");
	LOC1[2] = nimIntToStr((*bf).Khashes);
	nimln(94, "bloom.nim");
	LOC1[3] = nimIntToStr((*bf).Nbitsperelem);
	result = nsuFormatOpenArray(((NimStringDesc*) &TMP247), LOC1, 4);
	popFrame();
	return result;
}

N_NIMCALL(TY102153*, hashmurmur_102214)(tbloomfilter102009* bf, NimStringDesc* item) {
	TY102153* result;
	tmurmurhashes102007 murmurhashes;
	NI i_102262;
	NI HEX3Atmp_102263;
	NI res_102265;
	nimfr("hash_murmur", "bloom.nim")
	result = 0;
	nimln(99, "bloom.nim");
	result = newseq_102148((*bf).Khashes);
	nimln(100, "bloom.nim");
	chckNil((void*)murmurhashes);
	memset((void*)murmurhashes, 0, sizeof(murmurhashes));
	murmurhash_102028(item, ((NU32) 0), murmurhashes);
	i_102262 = 0;
	HEX3Atmp_102263 = 0;
	nimln(101, "bloom.nim");
	nimln(101, "bloom.nim");
	HEX3Atmp_102263 = (NI64)((*bf).Khashes - 1);
	nimln(1457, "system.nim");
	res_102265 = 0;
	nimln(1458, "system.nim");
	while (1) {
		nimln(1458, "system.nim");
		if (!(res_102265 <= HEX3Atmp_102263)) goto LA1;
		nimln(1457, "system.nim");
		i_102262 = res_102265;
		nimln(102, "bloom.nim");
		if ((NU)(i_102262) >= (NU)(result->Sup.len)) raiseIndexError();
		nimln(102, "bloom.nim");
		nimln(102, "bloom.nim");
		nimln(102, "bloom.nim");
		nimln(102, "bloom.nim");
		result->data[i_102262] = (NI64)((NI64)abs((NI64)(murmurhashes[(0)- 0] + (NI64)(i_102262 * murmurhashes[(1)- 0]))) % (*bf).Mbits);
		nimln(1460, "system.nim");
		res_102265 += 1;
	} LA1: ;
	nimln(103, "bloom.nim");
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(TY102153*, hashnimrod_102271)(tbloomfilter102009* bf, NimStringDesc* item) {
	TY102153* result_102276;
	TY102153* result;
	NI i_102305;
	NI HEX3Atmp_102307;
	NI TMP248;
	NI res_102309;
	nimfr("hash_nimrod", "bloom.nim")
	result_102276 = 0;
	result = 0;
	nimln(109, "bloom.nim");
	result = (TY102153*) newSeq((&NTI102153), (*bf).Khashes);
	i_102305 = 0;
	HEX3Atmp_102307 = 0;
	nimln(110, "bloom.nim");
	nimln(110, "bloom.nim");
	TMP248 = subInt((*bf).Khashes, 1);
	HEX3Atmp_102307 = (NI64)(TMP248);
	nimln(1457, "system.nim");
	res_102309 = 0;
	nimln(1458, "system.nim");
	while (1) {
		nimln(1458, "system.nim");
		if (!(res_102309 <= HEX3Atmp_102307)) goto LA1;
		nimln(1457, "system.nim");
		i_102305 = res_102309;
		nimln(111, "bloom.nim");
		if ((NU)(i_102305) >= (NU)(result->Sup.len)) raiseIndexError();
		result->data[i_102305] = hashn_102054(item, i_102305, (*bf).Mbits);
		nimln(1460, "system.nim");
		res_102309 = addInt(res_102309, 1);
	} LA1: ;
	nimln(112, "bloom.nim");
	nimln(112, "bloom.nim");
	genericSeqAssign(&result_102276, result, (&NTI102153));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result_102276;
}

N_NIMCALL(TY102153*, hash_102314)(tbloomfilter102009* bf, NimStringDesc* item) {
	TY102153* result;
	nimfr("hash", "bloom.nim")
	result = 0;
	nimln(115, "bloom.nim");
	{
		if (!(*bf).Usemurmurhash) goto LA3;
		nimln(116, "bloom.nim");
		result = hashmurmur_102214(bf, item);
	}
	goto LA1;
	LA3: ;
	{
		nimln(118, "bloom.nim");
		result = hashnimrod_102271(bf, item);
	}
	LA1: ;
	nimln(119, "bloom.nim");
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, insert_102322)(tbloomfilter102009* bf, NimStringDesc* item) {
	TY102153* hashset;
	NI h_102414;
	NI i_102421;
	NI l_102423;
	nimfr("insert", "bloom.nim")
	nimln(123, "bloom.nim");
	hashset = hash_102314(&(*bf), item);
	h_102414 = 0;
	nimln(2795, "system.nim");
	i_102421 = 0;
	nimln(2796, "system.nim");
	nimln(2796, "system.nim");
	l_102423 = hashset->Sup.len;
	nimln(2797, "system.nim");
	while (1) {
		NI intaddress;
		NI TMP249;
		NI bitoffset;
		NI TMP250;
		nimln(2797, "system.nim");
		if (!(i_102421 < l_102423)) goto LA1;
		nimln(2798, "system.nim");
		if ((NU)(i_102421) >= (NU)(hashset->Sup.len)) raiseIndexError();
		h_102414 = hashset->data[i_102421];
		nimln(125, "bloom.nim");
		nimln(125, "bloom.nim");
		TMP249 = divInt(h_102414, 64);
		intaddress = (NI64)(TMP249);
		nimln(126, "bloom.nim");
		nimln(126, "bloom.nim");
		TMP250 = modInt(h_102414, 64);
		bitoffset = (NI64)(TMP250);
		nimln(127, "bloom.nim");
		if ((NU)(intaddress) >= (NU)((*bf).Intarray->Sup.len)) raiseIndexError();
		nimln(127, "bloom.nim");
		if ((NU)(intaddress) >= (NU)((*bf).Intarray->Sup.len)) raiseIndexError();
		nimln(127, "bloom.nim");
		(*bf).Intarray->data[intaddress] = (NI)((*bf).Intarray->data[intaddress] | (NI)((NU64)(1) << (NU64)(((NI) (bitoffset)))));
		nimln(2799, "system.nim");
		i_102421 = addInt(i_102421, 1);
		nimln(2800, "system.nim");
		{
			nimln(2800, "system.nim");
			nimln(2800, "system.nim");
			nimln(2800, "system.nim");
			if (!!((hashset->Sup.len == l_102423))) goto LA4;
			nimln(2800, "system.nim");
			failedassertimpl_80021(((NimStringDesc*) &TMP251));
		}
		LA4: ;
	} LA1: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, lookup_102427)(tbloomfilter102009* bf, NimStringDesc* item) {
	NIM_BOOL result;
	TY102153* hashset;
	NI h_102445;
	NI i_102453;
	NI l_102455;
	nimfr("lookup", "bloom.nim")
	result = 0;
	nimln(133, "bloom.nim");
	hashset = hash_102314(bf, item);
	h_102445 = 0;
	nimln(2795, "system.nim");
	i_102453 = 0;
	nimln(2796, "system.nim");
	nimln(2796, "system.nim");
	l_102455 = hashset->Sup.len;
	nimln(2797, "system.nim");
	while (1) {
		NI intaddress;
		NI TMP252;
		NI bitoffset;
		NI TMP253;
		NI currentint;
		nimln(2797, "system.nim");
		if (!(i_102453 < l_102455)) goto LA1;
		nimln(2798, "system.nim");
		if ((NU)(i_102453) >= (NU)(hashset->Sup.len)) raiseIndexError();
		h_102445 = hashset->data[i_102453];
		nimln(135, "bloom.nim");
		nimln(135, "bloom.nim");
		TMP252 = divInt(h_102445, 64);
		intaddress = (NI64)(TMP252);
		nimln(136, "bloom.nim");
		nimln(136, "bloom.nim");
		TMP253 = modInt(h_102445, 64);
		bitoffset = (NI64)(TMP253);
		nimln(137, "bloom.nim");
		if ((NU)(intaddress) >= (NU)((*bf).Intarray->Sup.len)) raiseIndexError();
		currentint = (*bf).Intarray->data[intaddress];
		nimln(138, "bloom.nim");
		{
			nimln(138, "bloom.nim");
			nimln(138, "bloom.nim");
			nimln(138, "bloom.nim");
			nimln(138, "bloom.nim");
			if (!!((currentint == (NI)(currentint | (NI)((NU64)(1) << (NU64)(((NI) (bitoffset)))))))) goto LA4;
			nimln(139, "bloom.nim");
			nimln(139, "bloom.nim");
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA4: ;
		nimln(2799, "system.nim");
		i_102453 = addInt(i_102453, 1);
		nimln(2800, "system.nim");
		{
			nimln(2800, "system.nim");
			nimln(2800, "system.nim");
			nimln(2800, "system.nim");
			if (!!((hashset->Sup.len == l_102455))) goto LA8;
			nimln(2800, "system.nim");
			failedassertimpl_80021(((NimStringDesc*) &TMP251));
		}
		LA8: ;
	} LA1: ;
	nimln(140, "bloom.nim");
	nimln(140, "bloom.nim");
	result = NIM_TRUE;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41490* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44843(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41490* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44843((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46402(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NF, HEX2F_79238)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2566, "system.nim");
	nimln(2566, "system.nim");
	nimln(2566, "system.nim");
	nimln(2566, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	parseutilsDatInit();
	strutilsDatInit();
	timesDatInit();
	mathDatInit();
	hashesDatInit();
	probabilitiesDatInit();
	bloomDatInit();
	initStackBottom();
	parseutilsInit();
	strutilsInit();
	timesInit();
	mathInit();
	hashesInit();
	probabilitiesInit();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	bloomInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_NOINLINE(void, bloomInit)(void) {
	NimStringDesc* LOC29;
	NimStringDesc* LOC34;
	NIM_BOOL LOC35;
	NimStringDesc* LOC36;
	NIM_BOOL LOC37;
	NimStringDesc* LOC38;
	NimStringDesc* LOC44;
	NI HEX3Atmp_105609;
	NI TMP270;
	NI res_105611;
	NI HEX3Atmp_105615;
	NI TMP272;
	NI res_105617;
	NimStringDesc* LOC50;
	NimStringDesc* LOC51;
	NI HEX3Atmp_105622;
	NI TMP276;
	NI res_105624;
	NimStringDesc* LOC60;
	NimStringDesc* LOC61;
	NF LOC62;
	NimStringDesc* LOC63;
	NI HEX3Atmp_105626;
	NI TMP280;
	NI res_105628;
	NimStringDesc* LOC70;
	NimStringDesc* LOC71;
	NimStringDesc* LOC72;
	TSafePoint TMP283;
	nimfr("bloom", "bloom.nim")
	nimln(145, "bloom.nim");
	printf("%s\012", (((NimStringDesc*) &TMP254))->data);
	nimln(147, "bloom.nim");
	memcpy((void*)hashoutputs_102459, (NIM_CONST void*)TMP230, sizeof(hashoutputs_102459));
	nimln(148, "bloom.nim");
	MurmurHash3_x64_128("hello", 5, ((NU32) 0), hashoutputs_102459);
	nimln(149, "bloom.nim");
	{
		nimln(149, "bloom.nim");
		nimln(149, "bloom.nim");
		if (!!((((NI64) (hashoutputs_102459[(0)- 0])) == IL64(-3758069500696749310)))) goto LA3;
		nimln(149, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP255));
	}
	LA3: ;
	nimln(150, "bloom.nim");
	{
		nimln(150, "bloom.nim");
		nimln(150, "bloom.nim");
		if (!!((((NI64) (hashoutputs_102459[(1)- 0])) == IL64(6565844092913065241)))) goto LA7;
		nimln(150, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP256));
	}
	LA7: ;
	nimln(152, "bloom.nim");
	chckNil((void*)hashoutputs2_102801);
	genericReset((void*)hashoutputs2_102801, (&NTI102007));
	murmurhash_102028(((NimStringDesc*) &TMP257), ((NU32) 0), hashoutputs2_102801);
	nimln(153, "bloom.nim");
	{
		nimln(153, "bloom.nim");
		nimln(153, "bloom.nim");
		if (!!((hashoutputs2_102801[(0)- 0] == hashoutputs_102459[(0)- 0]))) goto LA11;
		nimln(153, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP258));
	}
	LA11: ;
	nimln(154, "bloom.nim");
	{
		nimln(154, "bloom.nim");
		nimln(154, "bloom.nim");
		if (!!((hashoutputs2_102801[(1)- 0] == hashoutputs_102459[(1)- 0]))) goto LA15;
		nimln(154, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP259));
	}
	LA15: ;
	nimln(155, "bloom.nim");
	chckNil((void*)hashoutputs3_103201);
	genericReset((void*)hashoutputs3_103201, (&NTI102007));
	murmurhash_102028(((NimStringDesc*) &TMP257), ((NU32) 10), hashoutputs3_103201);
	nimln(156, "bloom.nim");
	{
		nimln(156, "bloom.nim");
		nimln(156, "bloom.nim");
		nimln(156, "bloom.nim");
		if (!!(!((hashoutputs3_103201[(0)- 0] == hashoutputs_102459[(0)- 0])))) goto LA19;
		nimln(156, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP260));
	}
	LA19: ;
	nimln(157, "bloom.nim");
	{
		nimln(157, "bloom.nim");
		nimln(157, "bloom.nim");
		nimln(157, "bloom.nim");
		if (!!(!((hashoutputs3_103201[(1)- 0] == hashoutputs_102459[(1)- 0])))) goto LA23;
		nimln(157, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP261));
	}
	LA23: ;
	nimln(160, "bloom.nim");
	nelementstotest_103602 = 10000000;
	nimln(161, "bloom.nim");
	chckNil((void*)&bf_103604);
	genericReset((void*)&bf_103604, (&NTI102009));
	initializebloomfilter_102128(nelementstotest_103602, 1.0000000000000000e-03, 5, 0, NIM_TRUE, &bf_103604);
	nimln(162, "bloom.nim");
	{
		if (!NIM_FALSE) goto LA27;
		nimln(162, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP262));
	}
	LA27: ;
	nimln(163, "bloom.nim");
	nimln(163, "bloom.nim");
	LOC29 = 0;
	LOC29 = HEX24_102203(&bf_103604);
	printf("%s\012", (LOC29)->data);
	nimln(165, "bloom.nim");
	chckNil((void*)&bf2_103804);
	genericReset((void*)&bf2_103804, (&NTI102009));
	initializebloomfilter_102128(10000, 1.0000000000000000e-03, 4, 20, NIM_TRUE, &bf2_103804);
	nimln(166, "bloom.nim");
	{
		if (!NIM_FALSE) goto LA32;
		nimln(166, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP263));
	}
	LA32: ;
	nimln(167, "bloom.nim");
	nimln(167, "bloom.nim");
	LOC34 = 0;
	LOC34 = HEX24_102203(&bf2_103804);
	printf("%s\012", (LOC34)->data);
	nimln(169, "bloom.nim");
	printf("%s\012", (((NimStringDesc*) &TMP264))->data);
	nimln(170, "bloom.nim");
	nimln(170, "bloom.nim");
	nimln(170, "bloom.nim");
	LOC35 = 0;
	LOC35 = lookup_102427(&bf2_103804, ((NimStringDesc*) &TMP266));
	LOC36 = 0;
	LOC36 = nimBoolToStr(LOC35);
	printf("%s%s\012", (((NimStringDesc*) &TMP265))->data, (LOC36)->data);
	nimln(171, "bloom.nim");
	printf("%s\012", (((NimStringDesc*) &TMP267))->data);
	nimln(172, "bloom.nim");
	insert_102322(&bf2_103804, ((NimStringDesc*) &TMP266));
	nimln(173, "bloom.nim");
	nimln(173, "bloom.nim");
	nimln(173, "bloom.nim");
	LOC37 = 0;
	LOC37 = lookup_102427(&bf2_103804, ((NimStringDesc*) &TMP266));
	LOC38 = 0;
	LOC38 = nimBoolToStr(LOC37);
	printf("%s%s\012", (((NimStringDesc*) &TMP265))->data, (LOC38)->data);
	nimln(174, "bloom.nim");
	{
		NIM_BOOL LOC41;
		nimln(174, "bloom.nim");
		nimln(174, "bloom.nim");
		LOC41 = 0;
		LOC41 = lookup_102427(&bf2_103804, ((NimStringDesc*) &TMP266));
		if (!!(LOC41)) goto LA42;
		nimln(174, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP268));
	}
	LA42: ;
	nimln(177, "bloom.nim");
	randomize_98005(2882);
	nimln(178, "bloom.nim");
	LOC44 = 0;
	LOC44 = samplechars_104202; samplechars_104202 = copyStringRC1(((NimStringDesc*) &TMP269));
	if (LOC44) nimGCunrefNoCycle(LOC44);
	nimln(180, "bloom.nim");
	asgnRefNoCycle((void**) &ktestelements_104204, newseq_104208(nelementstotest_103602));
	nimln(181, "bloom.nim");
	asgnRefNoCycle((void**) &sampleletters_104205, newseq_104208(62));
	HEX3Atmp_105609 = 0;
	nimln(183, "bloom.nim");
	nimln(183, "bloom.nim");
	TMP270 = subInt(nelementstotest_103602, 1);
	HEX3Atmp_105609 = (NI64)(TMP270);
	nimln(1457, "system.nim");
	res_105611 = 0;
	nimln(1458, "system.nim");
	while (1) {
		NimStringDesc* newstring;
		NI res_105607;
		NimStringDesc* LOC48;
		nimln(1458, "system.nim");
		if (!(res_105611 <= HEX3Atmp_105609)) goto LA45;
		nimln(1457, "system.nim");
		i_104296 = res_105611;
		nimln(184, "bloom.nim");
		newstring = copyString(((NimStringDesc*) &TMP271));
		j_104308 = 0;
		nimln(1457, "system.nim");
		res_105607 = 0;
		nimln(1458, "system.nim");
		while (1) {
			NI LOC47;
			nimln(1458, "system.nim");
			if (!(res_105607 <= 7)) goto LA46;
			nimln(1457, "system.nim");
			j_104308 = res_105607;
			nimln(186, "bloom.nim");
			nimln(186, "bloom.nim");
			LOC47 = 0;
			LOC47 = random_97979(51);
			if ((NU)(LOC47) > (NU)(samplechars_104202->Sup.len)) raiseIndexError();
			newstring = addChar(newstring, samplechars_104202->data[LOC47]);
			nimln(1460, "system.nim");
			res_105607 = addInt(res_105607, 1);
		} LA46: ;
		nimln(187, "bloom.nim");
		if ((NU)(i_104296) >= (NU)(ktestelements_104204->Sup.len)) raiseIndexError();
		LOC48 = 0;
		LOC48 = ktestelements_104204->data[i_104296]; ktestelements_104204->data[i_104296] = copyStringRC1(newstring);
		if (LOC48) nimGCunrefNoCycle(LOC48);
		nimln(1460, "system.nim");
		res_105611 = addInt(res_105611, 1);
	} LA45: ;
	nimln(190, "bloom.nim");
	starttime_104310 = ntcpuTime();
	HEX3Atmp_105615 = 0;
	nimln(191, "bloom.nim");
	nimln(191, "bloom.nim");
	TMP272 = subInt(nelementstotest_103602, 1);
	HEX3Atmp_105615 = (NI64)(TMP272);
	nimln(1457, "system.nim");
	res_105617 = 0;
	nimln(1458, "system.nim");
	while (1) {
		nimln(1458, "system.nim");
		if (!(res_105617 <= HEX3Atmp_105615)) goto LA49;
		nimln(1457, "system.nim");
		i_104322 = res_105617;
		nimln(192, "bloom.nim");
		if ((NU)(i_104322) >= (NU)(ktestelements_104204->Sup.len)) raiseIndexError();
		insert_102322(&bf_103604, ktestelements_104204->data[i_104322]);
		nimln(1460, "system.nim");
		res_105617 = addInt(res_105617, 1);
	} LA49: ;
	nimln(193, "bloom.nim");
	endtime_104311 = ntcpuTime();
	nimln(194, "bloom.nim");
	nimln(194, "bloom.nim");
	nimln(194, "bloom.nim");
	LOC50 = 0;
	LOC50 = nsuformatFloat(((NF)(endtime_104311) - (NF)(starttime_104310)), ((NU8) 1), 4);
	nimln(194, "bloom.nim");
	LOC51 = 0;
	LOC51 = nimIntToStr(nelementstotest_103602);
	printf("%s%s%s%s%s\012", (((NimStringDesc*) &TMP273))->data, (LOC50)->data, (((NimStringDesc*) &TMP274))->data, (LOC51)->data, (((NimStringDesc*) &TMP275))->data);
	nimln(196, "bloom.nim");
	falsepositives_104324 = 0;
	HEX3Atmp_105622 = 0;
	nimln(197, "bloom.nim");
	nimln(197, "bloom.nim");
	TMP276 = subInt(nelementstotest_103602, 1);
	HEX3Atmp_105622 = (NI64)(TMP276);
	nimln(1457, "system.nim");
	res_105624 = 0;
	nimln(1458, "system.nim");
	while (1) {
		NimStringDesc* falsepositivestring;
		NI res_105620;
		nimln(1458, "system.nim");
		if (!(res_105624 <= HEX3Atmp_105622)) goto LA52;
		nimln(1457, "system.nim");
		i_104335 = res_105624;
		nimln(198, "bloom.nim");
		falsepositivestring = copyString(((NimStringDesc*) &TMP271));
		j_104347 = 0;
		nimln(1457, "system.nim");
		res_105620 = 0;
		nimln(1458, "system.nim");
		while (1) {
			NI LOC54;
			nimln(1458, "system.nim");
			if (!(res_105620 <= 8)) goto LA53;
			nimln(1457, "system.nim");
			j_104347 = res_105620;
			nimln(200, "bloom.nim");
			nimln(200, "bloom.nim");
			LOC54 = 0;
			LOC54 = random_97979(51);
			if ((NU)(LOC54) > (NU)(samplechars_104202->Sup.len)) raiseIndexError();
			falsepositivestring = addChar(falsepositivestring, samplechars_104202->data[LOC54]);
			nimln(1460, "system.nim");
			res_105620 = addInt(res_105620, 1);
		} LA53: ;
		nimln(201, "bloom.nim");
		{
			NIM_BOOL LOC57;
			nimln(201, "bloom.nim");
			LOC57 = 0;
			LOC57 = lookup_102427(&bf_103604, falsepositivestring);
			if (!LOC57) goto LA58;
			nimln(202, "bloom.nim");
			falsepositives_104324 = addInt(falsepositives_104324, 1);
		}
		LA58: ;
		nimln(1460, "system.nim");
		res_105624 = addInt(res_105624, 1);
	} LA52: ;
	nimln(204, "bloom.nim");
	nimln(204, "bloom.nim");
	LOC60 = 0;
	LOC60 = nimIntToStr(nelementstotest_103602);
	nimln(204, "bloom.nim");
	LOC61 = 0;
	LOC61 = nimIntToStr(falsepositives_104324);
	printf("%s%s%s%s\012", (((NimStringDesc*) &TMP277))->data, (LOC60)->data, (((NimStringDesc*) &TMP278))->data, (LOC61)->data);
	nimln(205, "bloom.nim");
	nimln(205, "bloom.nim");
	nimln(205, "bloom.nim");
	LOC62 = 0;
	LOC62 = HEX2F_79238(falsepositives_104324, nelementstotest_103602);
	LOC63 = 0;
	LOC63 = nsuformatFloat(LOC62, ((NU8) 1), 4);
	printf("%s%s\012", (((NimStringDesc*) &TMP279))->data, (LOC63)->data);
	nimln(207, "bloom.nim");
	lookuperrors_104360 = 0;
	nimln(208, "bloom.nim");
	starttime_104310 = ntcpuTime();
	HEX3Atmp_105626 = 0;
	nimln(209, "bloom.nim");
	nimln(209, "bloom.nim");
	TMP280 = subInt(nelementstotest_103602, 1);
	HEX3Atmp_105626 = (NI64)(TMP280);
	nimln(1457, "system.nim");
	res_105628 = 0;
	nimln(1458, "system.nim");
	while (1) {
		nimln(1458, "system.nim");
		if (!(res_105628 <= HEX3Atmp_105626)) goto LA64;
		nimln(1457, "system.nim");
		i_104371 = res_105628;
		nimln(210, "bloom.nim");
		{
			NIM_BOOL LOC67;
			nimln(210, "bloom.nim");
			nimln(210, "bloom.nim");
			if ((NU)(i_104371) >= (NU)(ktestelements_104204->Sup.len)) raiseIndexError();
			LOC67 = 0;
			LOC67 = lookup_102427(&bf_103604, ktestelements_104204->data[i_104371]);
			if (!!(LOC67)) goto LA68;
			nimln(211, "bloom.nim");
			lookuperrors_104360 = addInt(lookuperrors_104360, 1);
		}
		LA68: ;
		nimln(1460, "system.nim");
		res_105628 = addInt(res_105628, 1);
	} LA64: ;
	nimln(212, "bloom.nim");
	endtime_104311 = ntcpuTime();
	nimln(213, "bloom.nim");
	nimln(213, "bloom.nim");
	nimln(213, "bloom.nim");
	LOC70 = 0;
	LOC70 = nsuformatFloat(((NF)(endtime_104311) - (NF)(starttime_104310)), ((NU8) 1), 4);
	nimln(213, "bloom.nim");
	LOC71 = 0;
	LOC71 = nimIntToStr(nelementstotest_103602);
	printf("%s%s%s%s%s\012", (((NimStringDesc*) &TMP273))->data, (LOC70)->data, (((NimStringDesc*) &TMP281))->data, (LOC71)->data, (((NimStringDesc*) &TMP275))->data);
	nimln(215, "bloom.nim");
	nimln(215, "bloom.nim");
	LOC72 = 0;
	LOC72 = nimIntToStr(lookuperrors_104360);
	printf("%s%s\012", (((NimStringDesc*) &TMP282))->data, (LOC72)->data);
	nimln(218, "bloom.nim");
	pushSafePoint(&TMP283);
	TMP283.status = setjmp(TMP283.context);
	if (TMP283.status == 0) {
		NI volatile m1;
		nimln(219, "bloom.nim");
		m1 = getmovernbitsfork_102062(2, 1.0000000000000001e-05, kerrors_101013);
		nimln(220, "bloom.nim");
		{
			if (!NIM_TRUE) goto LA76;
			nimln(220, "bloom.nim");
			failedassertimpl_80021(((NimStringDesc*) &TMP284));
		}
		LA76: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI102005))) {
			TMP283.status = 0;
			nimln(222, "bloom.nim");
			{
				if (!NIM_FALSE) goto LA82;
				nimln(222, "bloom.nim");
				failedassertimpl_80021(((NimStringDesc*) &TMP285));
			}
			LA82: ;
			popCurrentException();
		}
	}
	if (TMP283.status != 0) reraiseException();
	nimln(224, "bloom.nim");
	{
		NI LOC86;
		nimln(224, "bloom.nim");
		nimln(224, "bloom.nim");
		nimln(224, "bloom.nim");
		LOC86 = 0;
		LOC86 = getmovernbitsfork_102062(2, 1.0000000000000001e-01, kerrors_101013);
		if (!!((LOC86 == 6))) goto LA87;
		nimln(224, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP286));
	}
	LA87: ;
	nimln(225, "bloom.nim");
	{
		NI LOC91;
		nimln(225, "bloom.nim");
		nimln(225, "bloom.nim");
		nimln(225, "bloom.nim");
		LOC91 = 0;
		LOC91 = getmovernbitsfork_102062(7, 1.0000000000000000e-02, kerrors_101013);
		if (!!((LOC91 == 10))) goto LA92;
		nimln(225, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP287));
	}
	LA92: ;
	nimln(226, "bloom.nim");
	{
		NI LOC96;
		nimln(226, "bloom.nim");
		nimln(226, "bloom.nim");
		nimln(226, "bloom.nim");
		LOC96 = 0;
		LOC96 = getmovernbitsfork_102062(7, 1.0000000000000000e-03, kerrors_101013);
		if (!!((LOC96 == 16))) goto LA97;
		nimln(226, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP288));
	}
	LA97: ;
	nimln(228, "bloom.nim");
	chckNil((void*)&bf3_105204);
	genericReset((void*)&bf3_105204, (&NTI102009));
	initializebloomfilter_102128(1000, 1.0000000000000000e-02, 4, 0, NIM_TRUE, &bf3_105204);
	nimln(229, "bloom.nim");
	{
		nimln(229, "bloom.nim");
		nimln(229, "bloom.nim");
		if (!!((bf3_105204.Nbitsperelem == 11))) goto LA101;
		nimln(229, "bloom.nim");
		failedassertimpl_80021(((NimStringDesc*) &TMP289));
	}
	LA101: ;
	popFrame();
}

N_NOINLINE(void, bloomDatInit)(void) {
static TNimNode* TMP245[7];
static TNimNode TMP122[9];
NTI102005.size = sizeof(ebloomfilter102005);
NTI102005.kind = 17;
NTI102005.base = (&NTI2425);
TMP122[0].len = 0; TMP122[0].kind = 2;
NTI102005.node = &TMP122[0];
NTI102072.size = sizeof(ebloomfilter102005*);
NTI102072.kind = 22;
NTI102072.base = (&NTI102005);
NTI102072.marker = TMP237;
NTI102009.size = sizeof(tbloomfilter102009);
NTI102009.kind = 18;
NTI102009.base = 0;
NTI102009.flags = 2;
TMP245[0] = &TMP122[2];
TMP122[2].kind = 1;
TMP122[2].offset = offsetof(tbloomfilter102009, Capacity);
TMP122[2].typ = (&NTI106);
TMP122[2].name = "capacity";
TMP245[1] = &TMP122[3];
TMP122[3].kind = 1;
TMP122[3].offset = offsetof(tbloomfilter102009, Errorrate);
TMP122[3].typ = (&NTI126);
TMP122[3].name = "error_rate";
TMP245[2] = &TMP122[4];
TMP122[4].kind = 1;
TMP122[4].offset = offsetof(tbloomfilter102009, Khashes);
TMP122[4].typ = (&NTI106);
TMP122[4].name = "k_hashes";
TMP245[3] = &TMP122[5];
TMP122[5].kind = 1;
TMP122[5].offset = offsetof(tbloomfilter102009, Mbits);
TMP122[5].typ = (&NTI106);
TMP122[5].name = "m_bits";
TMP245[4] = &TMP122[6];
TMP122[6].kind = 1;
TMP122[6].offset = offsetof(tbloomfilter102009, Intarray);
TMP122[6].typ = (&NTI102153);
TMP122[6].name = "int_array";
TMP245[5] = &TMP122[7];
TMP122[7].kind = 1;
TMP122[7].offset = offsetof(tbloomfilter102009, Nbitsperelem);
TMP122[7].typ = (&NTI106);
TMP122[7].name = "n_bits_per_elem";
TMP245[6] = &TMP122[8];
TMP122[8].kind = 1;
TMP122[8].offset = offsetof(tbloomfilter102009, Usemurmurhash);
TMP122[8].typ = (&NTI134);
TMP122[8].name = "use_murmur_hash";
TMP122[1].len = 7; TMP122[1].kind = 2; TMP122[1].sons = &TMP245[0];
NTI102009.node = &TMP122[1];
NTI102007.size = sizeof(tmurmurhashes102007);
NTI102007.kind = 16;
NTI102007.base = (&NTI106);
NTI102007.flags = 3;
}

