/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/boyd/nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_parseutils.o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_parseutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"
N_NOINLINE(void, pureparseutilsInit)(void) {
}

N_NOINLINE(void, pureparseutilsDatInit)(void) {
}

