/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/boyd/nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_strutils.o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_strutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct einvalidvalue1053 einvalidvalue1053;
typedef struct esynch1029 esynch1029;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38448 tcell38448;
typedef struct tcellseq38464 tcellseq38464;
typedef struct tgcheap40416 tgcheap40416;
typedef struct tcellset38460 tcellset38460;
typedef struct tpagedesc38456 tpagedesc38456;
typedef struct tmemregion21810 tmemregion21810;
typedef struct tsmallchunk21038 tsmallchunk21038;
typedef struct tllchunk21804 tllchunk21804;
typedef struct tbigchunk21040 tbigchunk21040;
typedef struct tintset21015 tintset21015;
typedef struct ttrunk21011 ttrunk21011;
typedef struct tavlnode21808 tavlnode21808;
typedef struct tgcstat40414 tgcstat40414;
typedef struct tbasechunk21036 tbasechunk21036;
typedef struct tfreecell21028 tfreecell21028;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct E_Base {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct esynch1029 {
  E_Base Sup;
};
struct einvalidvalue1053 {
  esynch1029 Sup;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38448 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38464 {
NI Len;
NI Cap;
tcell38448** D;
};
struct tcellset38460 {
NI Counter;
NI Max;
tpagedesc38456* Head;
tpagedesc38456** Data;
};
typedef tsmallchunk21038* TY21822[512];
typedef ttrunk21011* ttrunkbuckets21013[256];
struct tintset21015 {
ttrunkbuckets21013 Data;
};
struct tmemregion21810 {
NI Minlargeobj;
NI Maxlargeobj;
TY21822 Freesmallchunks;
tllchunk21804* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21040* Freechunkslist;
tintset21015 Chunkstarts;
tavlnode21808* Root;
tavlnode21808* Deleted;
tavlnode21808* Last;
tavlnode21808* Freeavlnodes;
};
struct tgcstat40414 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40416 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38464 Zct;
tcellseq38464 Decstack;
tcellset38460 Cycleroots;
tcellseq38464 Tempstack;
NI Recgclock;
tmemregion21810 Region;
tgcstat40414 Stat;
};
typedef NIM_CHAR TY85759[6];
typedef NIM_CHAR TY85762[2501];
typedef NIM_CHAR TY85755[3];
typedef NI TY21018[8];
struct tpagedesc38456 {
tpagedesc38456* Next;
NI Key;
TY21018 Bits;
};
struct tbasechunk21036 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21038 {
  tbasechunk21036 Sup;
tsmallchunk21038* Next;
tsmallchunk21038* Prev;
tfreecell21028* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk21804 {
NI Size;
NI Acc;
tllchunk21804* Next;
};
struct tbigchunk21040 {
  tbasechunk21036 Sup;
tbigchunk21040* Next;
tbigchunk21040* Prev;
NI Align;
NF Data;
};
struct ttrunk21011 {
ttrunk21011* Next;
NI Key;
TY21018 Bits;
};
typedef tavlnode21808* TY21814[2];
struct tavlnode21808 {
TY21814 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21028 {
tfreecell21028* Next;
NI Zerofield;
};
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, invalidformatstring_85825)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38448*, usrtocell_41839)(void* usr);
static N_INLINE(void, rtladdzct_43402)(tcell38448* c);
N_NOINLINE(void, addzct_41815)(tcellseq38464* s, tcell38448* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, findnormalized_85804)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_67023, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f, NU8 format, NI precision);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
STRING_LITERAL(TMP62, "invalid format string", 21);
NIM_CONST TY85755 floatformattochar_85754 = {103,
102,
101}
;
extern TNimType NTI16201; /* ref EInvalidValue */
extern TNimType NTI1053; /* EInvalidValue */
extern tgcheap40416 gch_40444;

static N_INLINE(tcell38448*, usrtocell_41839)(void* usr) {
	tcell38448* result;
	result = 0;
	result = ((tcell38448*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38448))))));
	return result;
}
static N_INLINE(void, rtladdzct_43402)(tcell38448* c) {
	addzct_41815(&gch_40444.Zct, c);}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38448* c;
	c = usrtocell_41839(p);
	{
		(*c).Refcount -= 8;
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		rtladdzct_43402(c);	}	LA3: ;
}
N_NOINLINE(void, invalidformatstring_85825)(void) {
	einvalidvalue1053* e_85829;
	NimStringDesc* LOC1;
	e_85829 = 0;
	e_85829 = (einvalidvalue1053*) newObj((&NTI16201), sizeof(einvalidvalue1053));
	(*e_85829).Sup.Sup.Sup.m_type = (&NTI1053);
	LOC1 = 0;
	LOC1 = (*e_85829).Sup.Sup.message; (*e_85829).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP62));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((E_Base*)e_85829, "EInvalidValue");
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));	(*dest).Sup.len += (*src).Sup.len;
}
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	result = 0;
	{
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		result = ((NIM_CHAR) (((NI) ((NI64)(((NI) (((NU8)(c)))) + 32)))));
	}	goto LA1;
	LA3: ;
	{
		result = c;
	}	LA1: ;
	return result;
}
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	result = 0;
	i = 0;
	j = 0;
	while (1) {
		NIM_CHAR aa;
		NIM_CHAR bb;
		while (1) {
			if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA2;
			i += 1;
		} LA2: ;
		while (1) {
			if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA3;
			j += 1;
		} LA3: ;
		aa = nsuToLowerChar(a->data[i]);
		bb = nsuToLowerChar(b->data[j]);
		result = (NI64)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
		{
			NIM_BOOL LOC6;
			LOC6 = 0;
			LOC6 = !((result == 0));
			if (LOC6) goto LA7;
			LOC6 = ((NU8)(aa) == (NU8)(0));
			LA7: ;
			if (!LOC6) goto LA8;
			goto LA1;
		}		LA8: ;
		i += 1;
		j += 1;
	} LA1: ;
	return result;
}
N_NIMCALL(NI, findnormalized_85804)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	result = 0;
	i = 0;
	while (1) {
		if (!(i < (inarrayLen0-1))) goto LA1;
		{
			NI LOC4;
			LOC4 = 0;
			LOC4 = nsuCmpIgnoreStyle(x, inarray[i]);
			if (!(LOC4 == 0)) goto LA5;
			result = i;
			goto BeforeRet;
		}		LA5: ;
		i += 2;
	} LA1: ;
	result = -1;
	goto BeforeRet;
	BeforeRet: ;	return result;
}
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	i = 0;
	num = 0;
	while (1) {
		if (!(i < formatstr->Sup.len)) goto LA1;
		{
			if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA4;
			switch (((NU8)(formatstr->data[(NI64)(i + 1)]))) {
			case 35:
			{
				{
					if (!((NU64)((aLen0-1)) < (NU64)(num))) goto LA9;
					invalidformatstring_85825();				}				LA9: ;
				(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
				i += 2;
				num += 1;
			}			break;
			case 36:
			{
				(*s) = addChar((*s), 36);
				i += 2;
			}			break;
			case 49 ... 57:
			case 45:
			{
				NI j;
				NIM_BOOL negative;
				NI idx;
				j = 0;
				i += 1;
				negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
				{
					if (!negative) goto LA15;
					i += 1;
				}				LA15: ;
				while (1) {
					if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA17;
					j = (NI64)((NI64)((NI64)(j * 10) + ((NI) (((NU8)(formatstr->data[i]))))) - 48);
					i += 1;
				} LA17: ;
				{
					if (!!(negative)) goto LA20;
					idx = (NI64)(j - 1);
				}				goto LA18;
				LA20: ;
				{
					idx = (NI64)(aLen0 - j);
				}				LA18: ;
				{
					if (!((NU64)((aLen0-1)) < (NU64)(idx))) goto LA25;
					invalidformatstring_85825();				}				LA25: ;
				(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
			}			break;
			case 123:
			{
				NI j;
				NI x;
				NimStringDesc* LOC29;
				j = (NI64)(i + 1);
				while (1) {
					if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA28;
					j += 1;
				} LA28: ;
				LOC29 = 0;
				LOC29 = copyStrLast(formatstr, (NI64)(i + 2), (NI64)(j - 1));
				x = findnormalized_85804(LOC29, a, aLen0);
				{
					NIM_BOOL LOC32;
					LOC32 = 0;
					LOC32 = (0 <= x);
					if (!(LOC32)) goto LA33;
					LOC32 = (x < (aLen0-1));
					LA33: ;
					if (!LOC32) goto LA34;
					(*s) = resizeString((*s), a[(NI64)(x + 1)]->Sup.len + 0);
appendString((*s), a[(NI64)(x + 1)]);
				}				goto LA30;
				LA34: ;
				{
					invalidformatstring_85825();				}				LA30: ;
				i = (NI64)(j + 1);
			}			break;
			case 97 ... 122:
			case 65 ... 90:
			case 128 ... 255:
			case 95:
			{
				NI j;
				NI x;
				NimStringDesc* LOC39;
				j = (NI64)(i + 1);
				while (1) {
					if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA38;
					j += 1;
				} LA38: ;
				LOC39 = 0;
				LOC39 = copyStrLast(formatstr, (NI64)(i + 1), (NI64)(j - 1));
				x = findnormalized_85804(LOC39, a, aLen0);
				{
					NIM_BOOL LOC42;
					LOC42 = 0;
					LOC42 = (0 <= x);
					if (!(LOC42)) goto LA43;
					LOC42 = (x < (aLen0-1));
					LA43: ;
					if (!LOC42) goto LA44;
					(*s) = resizeString((*s), a[(NI64)(x + 1)]->Sup.len + 0);
appendString((*s), a[(NI64)(x + 1)]);
				}				goto LA40;
				LA44: ;
				{
					invalidformatstring_85825();				}				LA40: ;
				i = j;
			}			break;
			default:
			{
				invalidformatstring_85825();			}			break;
			}
		}		goto LA2;
		LA4: ;
		{
			(*s) = addChar((*s), formatstr->data[i]);
			i += 1;
		}		LA2: ;
	} LA1: ;
}
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NimStringDesc* result;
	result = 0;
	result = rawNewString((NI64)(formatstr->Sup.len + (NI)((NU64)(aLen0) << (NU64)(4))));
	nsuAddf(&result, formatstr, a, aLen0);	return result;
}
N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f, NU8 format, NI precision) {
	NimStringDesc* result;
	TY85759 frmtstr;
	TY85762 buf;
	result = 0;
	frmtstr[(0)- 0] = 37;
	{
		if (!(0 < ((NI) (precision)))) goto LA3;
		frmtstr[(1)- 0] = 35;
		frmtstr[(2)- 0] = 46;
		frmtstr[(3)- 0] = 42;
		frmtstr[(4)- 0] = floatformattochar_85754[(format)- 0];
		frmtstr[(5)- 0] = 0;
		sprintf(((NCSTRING) (buf)), ((NCSTRING) (frmtstr)), precision, f);	}	goto LA1;
	LA3: ;
	{
		frmtstr[(1)- 0] = floatformattochar_85754[(format)- 0];
		frmtstr[(2)- 0] = 0;
		sprintf(((NCSTRING) (buf)), ((NCSTRING) (frmtstr)), f);	}	LA1: ;
	result = cstrToNimstr(((NCSTRING) (buf)));
	return result;
}
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, NU8 format, NI precision) {
	NimStringDesc* result;
	result = 0;
	result = nsuformatBiggestFloat(f, format, precision);
	return result;
}N_NOINLINE(void, purestrutilsInit)(void) {
}

N_NOINLINE(void, purestrutilsDatInit)(void) {
}

