/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/boyd/nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_hashes.o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_hashes.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
static N_INLINE(NI, HEX21HEX26_87005)(NI h, NI val);
static N_INLINE(NI, HEX21HEX24_87028)(NI h);

static N_INLINE(NI, HEX21HEX26_87005)(NI h, NI val) {
	NI result;
	result = 0;
	result = (NI)((NU64)(h) + (NU64)(val));
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(10))));
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(6)));
	return result;
}
static N_INLINE(NI, HEX21HEX24_87028)(NI h) {
	NI result;
	result = 0;
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(3))));
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(11)));
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(15))));
	return result;
}
N_NIMCALL(NI, hash_87827)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i_87841;
	NI HEX3Atmp_87850;
	NI res_87852;
	result = 0;
	h = 0;
	i_87841 = 0;
	HEX3Atmp_87850 = 0;
	HEX3Atmp_87850 = (NI64)(x->Sup.len - 1);
	res_87852 = 0;
	while (1) {
		if (!(res_87852 <= HEX3Atmp_87850)) goto LA1;
		i_87841 = res_87852;
		h = HEX21HEX26_87005(h, ((NI) (((NU8)(x->data[i_87841])))));
		res_87852 += 1;
	} LA1: ;
	result = HEX21HEX24_87028(h);
	return result;
}N_NOINLINE(void, purehashesInit)(void) {
}

N_NOINLINE(void, purehashesDatInit)(void) {
}

