/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/boyd/nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_times.o /Users/boyd/Projects/nimrod-bloom/nimcache/pure_times.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <time.h>

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}N_NOINLINE(void, puretimesInit)(void) {
}

N_NOINLINE(void, puretimesDatInit)(void) {
}

