/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/boyd/Applications/Nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_parseutils.o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_parseutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct tslice79292 tslice79292;
struct  tslice79292  {
NI A;
NI B;
};
static N_INLINE(void, HEX2AHEX3D_85724)(NF* x_85730, NF y_85733);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tslice79292, HEX2EHEX2E_86222)(NI a_86226, NI b_86228);
extern TFrame* frameptr_13238;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13238;
	frameptr_13238 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13238 = (*frameptr_13238).prev;
}

static N_INLINE(void, HEX2AHEX3D_85724)(NF* x_85730, NF y_85733) {
	nimfr("*=", "system.nim")
	nimln(2713, "system.nim");
	nimln(2713, "system.nim");
	(*x_85730) = ((NF)((*x_85730)) * (NF)(y_85733));
	popFrame();
}

static N_INLINE(tslice79292, HEX2EHEX2E_86222)(NI a_86226, NI b_86228) {
	tslice79292 result;
	nimfr("..", "system.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(179, "system.nim");
	result.A = a_86226;
	nimln(180, "system.nim");
	result.B = b_86228;
	popFrame();
	return result;
}
N_NOINLINE(void, parseutilsInit)(void) {
}

N_NOINLINE(void, parseutilsDatInit)(void) {
}

