/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/boyd/Applications/Nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_strutils.o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct einvalidvalue2453 einvalidvalue2453;
typedef struct esynch2429 esynch2429;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell41490 tcell41490;
typedef struct tcellseq41506 tcellseq41506;
typedef struct tgcheap43416 tgcheap43416;
typedef struct tcellset41502 tcellset41502;
typedef struct tpagedesc41498 tpagedesc41498;
typedef struct tmemregion23810 tmemregion23810;
typedef struct tsmallchunk23038 tsmallchunk23038;
typedef struct tllchunk23804 tllchunk23804;
typedef struct tbigchunk23040 tbigchunk23040;
typedef struct tintset23015 tintset23015;
typedef struct ttrunk23011 ttrunk23011;
typedef struct tavlnode23808 tavlnode23808;
typedef struct tgcstat43414 tgcstat43414;
typedef struct tbasechunk23036 tbasechunk23036;
typedef struct tfreecell23028 tfreecell23028;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2429  {
  E_Base Sup;
};
struct  einvalidvalue2453  {
  esynch2429 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell41490  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41506  {
NI Len;
NI Cap;
tcell41490** D;
};
struct  tcellset41502  {
NI Counter;
NI Max;
tpagedesc41498* Head;
tpagedesc41498** Data;
};
typedef tsmallchunk23038* TY23822[512];
typedef ttrunk23011* ttrunkbuckets23013[256];
struct  tintset23015  {
ttrunkbuckets23013 Data;
};
struct  tmemregion23810  {
NI Minlargeobj;
NI Maxlargeobj;
TY23822 Freesmallchunks;
tllchunk23804* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk23040* Freechunkslist;
tintset23015 Chunkstarts;
tavlnode23808* Root;
tavlnode23808* Deleted;
tavlnode23808* Last;
tavlnode23808* Freeavlnodes;
};
struct  tgcstat43414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41506 Zct;
tcellseq41506 Decstack;
tcellset41502 Cycleroots;
tcellseq41506 Tempstack;
NI Recgclock;
tmemregion23810 Region;
tgcstat43414 Stat;
};
typedef NIM_CHAR TY91547[6];
typedef NIM_CHAR TY91550[2501];
typedef NIM_CHAR TY91542[3];
typedef NI TY23018[8];
struct  tpagedesc41498  {
tpagedesc41498* Next;
NI Key;
TY23018 Bits;
};
struct  tbasechunk23036  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk23038  {
  tbasechunk23036 Sup;
tsmallchunk23038* Next;
tsmallchunk23038* Prev;
tfreecell23028* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23804  {
NI Size;
NI Acc;
tllchunk23804* Next;
};
struct  tbigchunk23040  {
  tbasechunk23036 Sup;
tbigchunk23040* Next;
tbigchunk23040* Prev;
NI Align;
NF Data;
};
struct  ttrunk23011  {
ttrunk23011* Next;
NI Key;
TY23018 Bits;
};
typedef tavlnode23808* TY23814[2];
struct  tavlnode23808  {
TY23814 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell23028  {
tfreecell23028* Next;
NI Zerofield;
};
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NOINLINE(void, invalidformatstring_91625)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell41490*, usrtocell_44843)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_46402)(tcell41490* c);
N_NOINLINE(void, addzct_44818)(tcellseq41506* s, tcell41490* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, findnormalized_91598)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_71024, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f, NU8 format, NI precision);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
STRING_LITERAL(TMP246, "invalid format string", 21);
NIM_CONST TY91542 floatformattochar_91541 = {103,
102,
101}
;
extern TNimType NTI18201; /* ref EInvalidValue */
extern TNimType NTI2453; /* EInvalidValue */
extern TFrame* frameptr_13238;
extern tgcheap43416 gch_43444;

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars) {
	NimStringDesc* result;
	NI i_89116;
	NI HEX3Atmp_89118;
	NI res_89120;
	result = 0;
	result = nimIntToStr((NI64)abs(x));
	i_89116 = 0;
	HEX3Atmp_89118 = 0;
	HEX3Atmp_89118 = (NI64)(minchars - result->Sup.len);
	res_89120 = 1;
	while (1) {
		NimStringDesc* LOC2;
		if (!(res_89120 <= HEX3Atmp_89118)) goto LA1;
		i_89116 = res_89120;
		LOC2 = 0;
		LOC2 = rawNewString(result->Sup.len + 1);
appendChar(LOC2, 48);
appendString(LOC2, result);
		result = LOC2;
		res_89120 += 1;
	} LA1: ;
	{
		NimStringDesc* LOC7;
		if (!(x < 0)) goto LA5;
		LOC7 = 0;
		LOC7 = rawNewString(result->Sup.len + 1);
appendChar(LOC7, 45);
appendString(LOC7, result);
		result = LOC7;
	}
	LA5: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c) {
	NimStringDesc* result;
	NI i_89463;
	NI HEX3Atmp_89464;
	NI res_89466;
	result = 0;
	result = mnewString(count);
	i_89463 = 0;
	HEX3Atmp_89464 = 0;
	HEX3Atmp_89464 = (NI64)(count - 1);
	res_89466 = 0;
	while (1) {
		if (!(res_89466 <= HEX3Atmp_89464)) goto LA1;
		i_89463 = res_89466;
		result->data[i_89463] = c;
		res_89466 += 1;
	} LA1: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13238;
	frameptr_13238 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13238 = (*frameptr_13238).prev;
}

static N_INLINE(tcell41490*, usrtocell_44843)(void* usr) {
	tcell41490* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41490*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41490))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46402)(tcell41490* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44818(&gch_43444.Zct, c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell41490* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_44843(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_46402(c);
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, invalidformatstring_91625)(void) {
	einvalidvalue2453* e_91629;
	NimStringDesc* LOC1;
	e_91629 = 0;
	e_91629 = (einvalidvalue2453*) newObj((&NTI18201), sizeof(einvalidvalue2453));
	(*e_91629).Sup.Sup.Sup.m_type = (&NTI2453);
	LOC1 = 0;
	LOC1 = (*e_91629).Sup.Sup.message; (*e_91629).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP246));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((E_Base*)e_91629, "EInvalidValue");
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c) {
	NIM_CHAR result;
	result = 0;
	{
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		result = ((NIM_CHAR) (((NI) ((NI64)(((NI) (((NU8)(c)))) + 32)))));
	}
	goto LA1;
	LA3: ;
	{
		result = c;
	}
	LA1: ;
	return result;
}

N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI i;
	NI j;
	result = 0;
	i = 0;
	j = 0;
	while (1) {
		NIM_CHAR aa;
		NIM_CHAR bb;
		while (1) {
			if (!((NU8)(a->data[i]) == (NU8)(95))) goto LA2;
			i += 1;
		} LA2: ;
		while (1) {
			if (!((NU8)(b->data[j]) == (NU8)(95))) goto LA3;
			j += 1;
		} LA3: ;
		aa = nsuToLowerChar(a->data[i]);
		bb = nsuToLowerChar(b->data[j]);
		result = (NI64)(((NI) (((NU8)(aa)))) - ((NI) (((NU8)(bb)))));
		{
			NIM_BOOL LOC6;
			LOC6 = 0;
			LOC6 = !((result == 0));
			if (LOC6) goto LA7;
			LOC6 = ((NU8)(aa) == (NU8)(0));
			LA7: ;
			if (!LOC6) goto LA8;
			goto LA1;
		}
		LA8: ;
		i += 1;
		j += 1;
	} LA1: ;
	return result;
}

N_NIMCALL(NI, findnormalized_91598)(NimStringDesc* x, NimStringDesc** inarray, NI inarrayLen0) {
	NI result;
	NI i;
	result = 0;
	i = 0;
	while (1) {
		if (!(i < (inarrayLen0-1))) goto LA1;
		{
			NI LOC4;
			LOC4 = 0;
			LOC4 = nsuCmpIgnoreStyle(x, inarray[i]);
			if (!(LOC4 == 0)) goto LA5;
			result = i;
			goto BeforeRet;
		}
		LA5: ;
		i += 2;
	} LA1: ;
	result = -1;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NI i;
	NI num;
	i = 0;
	num = 0;
	while (1) {
		if (!(i < formatstr->Sup.len)) goto LA1;
		{
			if (!((NU8)(formatstr->data[i]) == (NU8)(36))) goto LA4;
			switch (((NU8)(formatstr->data[(NI64)(i + 1)]))) {
			case 35:
			{
				{
					if (!((NU64)((aLen0-1)) < (NU64)(num))) goto LA9;
					invalidformatstring_91625();
				}
				LA9: ;
				(*s) = resizeString((*s), a[num]->Sup.len + 0);
appendString((*s), a[num]);
				i += 2;
				num += 1;
			}
			break;
			case 36:
			{
				(*s) = addChar((*s), 36);
				i += 2;
			}
			break;
			case 49 ... 57:
			case 45:
			{
				NI j;
				NIM_BOOL negative;
				NI idx;
				j = 0;
				i += 1;
				negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
				{
					if (!negative) goto LA15;
					i += 1;
				}
				LA15: ;
				while (1) {
					if (!(((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)))) goto LA17;
					j = (NI64)((NI64)((NI64)(j * 10) + ((NI) (((NU8)(formatstr->data[i]))))) - 48);
					i += 1;
				} LA17: ;
				{
					if (!!(negative)) goto LA20;
					idx = (NI64)(j - 1);
				}
				goto LA18;
				LA20: ;
				{
					idx = (NI64)(aLen0 - j);
				}
				LA18: ;
				{
					if (!((NU64)((aLen0-1)) < (NU64)(idx))) goto LA25;
					invalidformatstring_91625();
				}
				LA25: ;
				(*s) = resizeString((*s), a[idx]->Sup.len + 0);
appendString((*s), a[idx]);
			}
			break;
			case 123:
			{
				NI j;
				NI x;
				NimStringDesc* LOC29;
				j = (NI64)(i + 1);
				while (1) {
					if (!!((((NU8)(formatstr->data[j])) == ((NU8)(0)) || ((NU8)(formatstr->data[j])) == ((NU8)(125))))) goto LA28;
					j += 1;
				} LA28: ;
				LOC29 = 0;
				LOC29 = copyStrLast(formatstr, (NI64)(i + 2), (NI64)(j - 1));
				x = findnormalized_91598(LOC29, a, aLen0);
				{
					NIM_BOOL LOC32;
					LOC32 = 0;
					LOC32 = (0 <= x);
					if (!(LOC32)) goto LA33;
					LOC32 = (x < (aLen0-1));
					LA33: ;
					if (!LOC32) goto LA34;
					(*s) = resizeString((*s), a[(NI64)(x + 1)]->Sup.len + 0);
appendString((*s), a[(NI64)(x + 1)]);
				}
				goto LA30;
				LA34: ;
				{
					invalidformatstring_91625();
				}
				LA30: ;
				i = (NI64)(j + 1);
			}
			break;
			case 97 ... 122:
			case 65 ... 90:
			case 128 ... 255:
			case 95:
			{
				NI j;
				NI x;
				NimStringDesc* LOC39;
				j = (NI64)(i + 1);
				while (1) {
					if (!(((NU8)(formatstr->data[j])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j])) == ((NU8)(95)))) goto LA38;
					j += 1;
				} LA38: ;
				LOC39 = 0;
				LOC39 = copyStrLast(formatstr, (NI64)(i + 1), (NI64)(j - 1));
				x = findnormalized_91598(LOC39, a, aLen0);
				{
					NIM_BOOL LOC42;
					LOC42 = 0;
					LOC42 = (0 <= x);
					if (!(LOC42)) goto LA43;
					LOC42 = (x < (aLen0-1));
					LA43: ;
					if (!LOC42) goto LA44;
					(*s) = resizeString((*s), a[(NI64)(x + 1)]->Sup.len + 0);
appendString((*s), a[(NI64)(x + 1)]);
				}
				goto LA40;
				LA44: ;
				{
					invalidformatstring_91625();
				}
				LA40: ;
				i = j;
			}
			break;
			default:
			{
				invalidformatstring_91625();
			}
			break;
			}
		}
		goto LA2;
		LA4: ;
		{
			(*s) = addChar((*s), formatstr->data[i]);
			i += 1;
		}
		LA2: ;
	} LA1: ;
}

N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0) {
	NimStringDesc* result;
	result = 0;
	result = rawNewString((NI64)(formatstr->Sup.len + (NI)((NU64)(aLen0) << (NU64)(4))));
	nsuAddf(&result, formatstr, a, aLen0);
	return result;
}

N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f, NU8 format, NI precision) {
	NimStringDesc* result;
	TY91547 frmtstr;
	TY91550 buf;
	result = 0;
	frmtstr[(0)- 0] = 37;
	{
		if (!(0 < ((NI) (precision)))) goto LA3;
		frmtstr[(1)- 0] = 35;
		frmtstr[(2)- 0] = 46;
		frmtstr[(3)- 0] = 42;
		frmtstr[(4)- 0] = floatformattochar_91541[(format)- 0];
		frmtstr[(5)- 0] = 0;
		sprintf(((NCSTRING) (buf)), ((NCSTRING) (frmtstr)), precision, f);
	}
	goto LA1;
	LA3: ;
	{
		frmtstr[(1)- 0] = floatformattochar_91541[(format)- 0];
		frmtstr[(2)- 0] = 0;
		sprintf(((NCSTRING) (buf)), ((NCSTRING) (frmtstr)), f);
	}
	LA1: ;
	result = cstrToNimstr(((NCSTRING) (buf)));
	return result;
}

N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, NU8 format, NI precision) {
	NimStringDesc* result;
	result = 0;
	result = nsuformatBiggestFloat(f, format, precision);
	return result;
}
N_NOINLINE(void, strutilsInit)(void) {
}

N_NOINLINE(void, strutilsDatInit)(void) {
}

