/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/boyd/Applications/Nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_hashes.o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_hashes.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX21HEX26_99010)(NI h, NI val);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, HEX21HEX24_99035)(NI h);
N_NIMCALL(NI, hashdata_99059)(void* data, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(NI, hash_99401)(void* x);
static N_INLINE(NI, hash_99802)(NI x);
static N_INLINE(NI, hash_99808)(NI64 x);
static N_INLINE(NI, hash_99814)(NIM_CHAR x);
N_NIMCALL(NI, hash_99828)(NimStringDesc* x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, hashignorestyle_99860)(NimStringDesc* x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, hashignorecase_99936)(NimStringDesc* x);
static N_INLINE(NI, hash_100022)(NF x);
extern TFrame* frameptr_13238;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13238;
	frameptr_13238 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13238 = (*frameptr_13238).prev;
}

static N_INLINE(NI, HEX21HEX26_99010)(NI h, NI val) {
	NI result;
	nimfr("!&", "hashes.nim")
	result = 0;
	nimln(24, "hashes.nim");
	nimln(24, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)(val));
	nimln(25, "hashes.nim");
	nimln(25, "hashes.nim");
	nimln(25, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(10))));
	nimln(26, "hashes.nim");
	nimln(26, "hashes.nim");
	nimln(26, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(6)));
	popFrame();
	return result;
}

static N_INLINE(NI, HEX21HEX24_99035)(NI h) {
	NI result;
	nimfr("!$", "hashes.nim")
	result = 0;
	nimln(31, "hashes.nim");
	nimln(31, "hashes.nim");
	nimln(31, "hashes.nim");
	result = (NI)((NU64)(h) + (NU64)((NI)((NU64)(h) << (NU64)(3))));
	nimln(32, "hashes.nim");
	nimln(32, "hashes.nim");
	nimln(32, "hashes.nim");
	result = (NI)(result ^ (NI)((NU64)(result) >> (NU64)(11)));
	nimln(33, "hashes.nim");
	nimln(33, "hashes.nim");
	nimln(33, "hashes.nim");
	result = (NI)((NU64)(result) + (NU64)((NI)((NU64)(result) << (NU64)(15))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashdata_99059)(void* data, NI size) {
	NI result;
	NI h;
	NCSTRING p;
	NI i;
	NI s;
	nimfr("hashData", "hashes.nim")
	result = 0;
	nimln(37, "hashes.nim");
	h = 0;
	nimln(42, "hashes.nim");
	p = ((NCSTRING) (data));
	nimln(43, "hashes.nim");
	i = 0;
	nimln(44, "hashes.nim");
	s = size;
	nimln(45, "hashes.nim");
	while (1) {
		nimln(45, "hashes.nim");
		if (!(0 < s)) goto LA1;
		nimln(46, "hashes.nim");
		nimln(46, "hashes.nim");
		h = HEX21HEX26_99010(h, ((NI) (((NU8)(p[i])))));
		nimln(47, "hashes.nim");
		i = addInt(i, 1);
		nimln(48, "hashes.nim");
		s = subInt(s, 1);
	} LA1: ;
	nimln(49, "hashes.nim");
	result = HEX21HEX24_99035(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99401)(void* x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(68, "hashes.nim");
	nimln(68, "hashes.nim");
	result = (NI)((NU64)(((NI) (x))) >> (NU64)(3));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99802)(NI x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(80, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99808)(NI64 x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(84, "hashes.nim");
	nimln(84, "hashes.nim");
	result = ((NI) (((NI32)(NU32)(NU64)(x))));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_99814)(NIM_CHAR x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(88, "hashes.nim");
	nimln(88, "hashes.nim");
	result = ((NI) (((NU8)(x))));
	popFrame();
	return result;
}

N_NIMCALL(NI, hash_99828)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i_99843;
	NI HEX3Atmp_99853;
	NI TMP196;
	NI res_99855;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(92, "hashes.nim");
	h = 0;
	i_99843 = 0;
	HEX3Atmp_99853 = 0;
	nimln(93, "hashes.nim");
	nimln(93, "hashes.nim");
	nimln(93, "hashes.nim");
	TMP196 = subInt(x->Sup.len, 1);
	HEX3Atmp_99853 = (NI64)(TMP196);
	nimln(1457, "system.nim");
	res_99855 = 0;
	nimln(1458, "system.nim");
	while (1) {
		nimln(1458, "system.nim");
		if (!(res_99855 <= HEX3Atmp_99853)) goto LA1;
		nimln(1457, "system.nim");
		i_99843 = res_99855;
		nimln(94, "hashes.nim");
		nimln(94, "hashes.nim");
		if ((NU)(i_99843) > (NU)(x->Sup.len)) raiseIndexError();
		h = HEX21HEX26_99010(h, ((NI) (((NU8)(x->data[i_99843])))));
		nimln(1460, "system.nim");
		res_99855 = addInt(res_99855, 1);
	} LA1: ;
	nimln(95, "hashes.nim");
	result = HEX21HEX24_99035(h);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hashignorestyle_99860)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i_99875;
	NI HEX3Atmp_99928;
	NI TMP197;
	NI res_99930;
	nimfr("hashIgnoreStyle", "hashes.nim")
	result = 0;
	nimln(99, "hashes.nim");
	h = 0;
	i_99875 = 0;
	HEX3Atmp_99928 = 0;
	nimln(100, "hashes.nim");
	nimln(100, "hashes.nim");
	nimln(100, "hashes.nim");
	TMP197 = subInt(x->Sup.len, 1);
	HEX3Atmp_99928 = (NI64)(TMP197);
	nimln(1457, "system.nim");
	res_99930 = 0;
	nimln(1458, "system.nim");
	while (1) {
		nimln(1458, "system.nim");
		if (!(res_99930 <= HEX3Atmp_99928)) goto LA1;
		nimln(1457, "system.nim");
		i_99875 = res_99930;
		{
			NIM_CHAR c;
			nimln(101, "hashes.nim");
			if ((NU)(i_99875) > (NU)(x->Sup.len)) raiseIndexError();
			c = x->data[i_99875];
			nimln(102, "hashes.nim");
			{
				nimln(102, "hashes.nim");
				if (!((NU8)(c) == (NU8)(95))) goto LA5;
				nimln(103, "hashes.nim");
				goto LA2;
			}
			LA5: ;
			nimln(104, "hashes.nim");
			{
				NI TMP198;
				nimln(104, "hashes.nim");
				if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA9;
				nimln(105, "hashes.nim");
				nimln(105, "hashes.nim");
				nimln(105, "hashes.nim");
				nimln(105, "hashes.nim");
				TMP198 = addInt(((NI) (((NU8)(c)))), 32);
				c = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP198), 0, 255))));
			}
			LA9: ;
			nimln(106, "hashes.nim");
			nimln(106, "hashes.nim");
			h = HEX21HEX26_99010(h, ((NI) (((NU8)(c)))));
		} LA2: ;
		nimln(1460, "system.nim");
		res_99930 = addInt(res_99930, 1);
	} LA1: ;
	nimln(107, "hashes.nim");
	result = HEX21HEX24_99035(h);
	popFrame();
	return result;
}

N_NIMCALL(NI, hashignorecase_99936)(NimStringDesc* x) {
	NI result;
	NI h;
	NI i_99951;
	NI HEX3Atmp_100003;
	NI TMP199;
	NI res_100005;
	nimfr("hashIgnoreCase", "hashes.nim")
	result = 0;
	nimln(111, "hashes.nim");
	h = 0;
	i_99951 = 0;
	HEX3Atmp_100003 = 0;
	nimln(112, "hashes.nim");
	nimln(112, "hashes.nim");
	nimln(112, "hashes.nim");
	TMP199 = subInt(x->Sup.len, 1);
	HEX3Atmp_100003 = (NI64)(TMP199);
	nimln(1457, "system.nim");
	res_100005 = 0;
	nimln(1458, "system.nim");
	while (1) {
		NIM_CHAR c;
		nimln(1458, "system.nim");
		if (!(res_100005 <= HEX3Atmp_100003)) goto LA1;
		nimln(1457, "system.nim");
		i_99951 = res_100005;
		nimln(113, "hashes.nim");
		if ((NU)(i_99951) > (NU)(x->Sup.len)) raiseIndexError();
		c = x->data[i_99951];
		nimln(114, "hashes.nim");
		{
			NI TMP200;
			nimln(114, "hashes.nim");
			if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA4;
			nimln(115, "hashes.nim");
			nimln(115, "hashes.nim");
			nimln(115, "hashes.nim");
			nimln(115, "hashes.nim");
			TMP200 = addInt(((NI) (((NU8)(c)))), 32);
			c = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP200), 0, 255))));
		}
		LA4: ;
		nimln(116, "hashes.nim");
		nimln(116, "hashes.nim");
		h = HEX21HEX26_99010(h, ((NI) (((NU8)(c)))));
		nimln(1460, "system.nim");
		res_100005 = addInt(res_100005, 1);
	} LA1: ;
	nimln(117, "hashes.nim");
	result = HEX21HEX24_99035(h);
	popFrame();
	return result;
}

static N_INLINE(NI, hash_100022)(NF x) {
	NI result;
	NF y;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(126, "hashes.nim");
	nimln(126, "hashes.nim");
	y = ((NF)(x) + (NF)(1.0000000000000000e+00));
	nimln(127, "hashes.nim");
	result = (*((NI*) (&y)));
	popFrame();
	return result;
}
N_NOINLINE(void, hashesInit)(void) {
	nimfr("hashes", "hashes.nim")
	popFrame();
}

N_NOINLINE(void, hashesDatInit)(void) {
}

