/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/boyd/Applications/Nimrod/lib -o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_times.o /Users/boyd/Projects/nimrod-bloom/nimcache/stdlib_times.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <time.h>

#include <sys/time.h>

#include <string.h>

#include <sys/select.h>
typedef struct ttimeinterval94005 ttimeinterval94005;
typedef struct ttimeinfo94003 ttimeinfo94003;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY94106 TY94106;
typedef struct tslice79292 tslice79292;
typedef struct einvalidvalue2453 einvalidvalue2453;
typedef struct esynch2429 esynch2429;
typedef struct E_Base E_Base;
typedef struct tcell41490 tcell41490;
typedef struct tcellseq41506 tcellseq41506;
typedef struct tgcheap43416 tgcheap43416;
typedef struct tcellset41502 tcellset41502;
typedef struct tpagedesc41498 tpagedesc41498;
typedef struct tmemregion23810 tmemregion23810;
typedef struct tsmallchunk23038 tsmallchunk23038;
typedef struct tllchunk23804 tllchunk23804;
typedef struct tbigchunk23040 tbigchunk23040;
typedef struct tintset23015 tintset23015;
typedef struct ttrunk23011 ttrunk23011;
typedef struct tavlnode23808 tavlnode23808;
typedef struct tgcstat43414 tgcstat43414;
typedef struct tbasechunk23036 tbasechunk23036;
typedef struct tfreecell23028 tfreecell23028;
struct  ttimeinterval94005  {
NI Miliseconds;
NI Seconds;
NI Minutes;
NI Hours;
NI Days;
NI Months;
NI Years;
};
typedef N_NIMCALL_PTR(void, TY2289) (void* p, NI op);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY2289 marker;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  ttimeinfo94003  {
  TNimObject Sup;
NI Second;
NI Minute;
NI Hour;
NI Monthday;
NU8 Month;
NI Year;
NU8 Weekday;
NI Yearday;
NIM_BOOL Isdst;
NimStringDesc* Tzname;
NI Timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY94650[7];
struct TY94106 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY94669[7];
typedef NimStringDesc* TY95829[7];
typedef NimStringDesc* TY95841[12];
struct  tslice79292  {
NI A;
NI B;
};
struct  E_Base  {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  esynch2429  {
  E_Base Sup;
};
struct  einvalidvalue2453  {
  esynch2429 Sup;
};
struct  tcell41490  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq41506  {
NI Len;
NI Cap;
tcell41490** D;
};
struct  tcellset41502  {
NI Counter;
NI Max;
tpagedesc41498* Head;
tpagedesc41498** Data;
};
typedef tsmallchunk23038* TY23822[512];
typedef ttrunk23011* ttrunkbuckets23013[256];
struct  tintset23015  {
ttrunkbuckets23013 Data;
};
struct  tmemregion23810  {
NI Minlargeobj;
NI Maxlargeobj;
TY23822 Freesmallchunks;
tllchunk23804* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk23040* Freechunkslist;
tintset23015 Chunkstarts;
tavlnode23808* Root;
tavlnode23808* Deleted;
tavlnode23808* Last;
tavlnode23808* Freeavlnodes;
};
struct  tgcstat43414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap43416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq41506 Zct;
tcellseq41506 Decstack;
tcellset41502 Cycleroots;
tcellseq41506 Tempstack;
NI Recgclock;
tmemregion23810 Region;
tgcstat43414 Stat;
};
typedef NI TY23018[8];
struct  tpagedesc41498  {
tpagedesc41498* Next;
NI Key;
TY23018 Bits;
};
struct  tbasechunk23036  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk23038  {
  tbasechunk23036 Sup;
tsmallchunk23038* Next;
tsmallchunk23038* Prev;
tfreecell23028* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk23804  {
NI Size;
NI Acc;
tllchunk23804* Next;
};
struct  tbigchunk23040  {
  tbasechunk23036 Sup;
tbigchunk23040* Next;
tbigchunk23040* Prev;
NI Align;
NF Data;
};
struct  ttrunk23011  {
ttrunk23011* Next;
NI Key;
TY23018 Bits;
};
typedef tavlnode23808* TY23814[2];
struct  tavlnode23808  {
TY23814 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell23028  {
tfreecell23028* Next;
NI Zerofield;
};
N_NIMCALL(time_t, fromseconds_94057)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(ttimeinterval94005, initinterval_94208)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_94220)(NI year);
N_NIMCALL(NI, getdaysinmonth_94231)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_94275)(NF* x_94281, NF y_94284);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, toseconds_94240)(ttimeinfo94003* a, ttimeinterval94005* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_79238)(NI x, NI y);
N_NIMCALL(void, HEX2B_94407)(ttimeinfo94003* a, ttimeinterval94005* interval, ttimeinfo94003* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_94416)(ttimeinfo94003* a, ttimeinterval94005* interval, ttimeinfo94003* Result);
N_NIMCALL(void, tmtotimeinfo_94644)(struct tm* tm, NIM_BOOL local, ttimeinfo94003* Result);
N_NIMCALL(void, gettzname_94104)(TY94106* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_94202)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_94664)(ttimeinfo94003* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_94205)(void);
N_NIMCALL(time_t, gettime_94038)(void);
N_NIMCALL(void, getlocaltime_94041)(time_t t, ttimeinfo94003* Result);
N_NIMCALL(void, getgmtime_94045)(time_t t, ttimeinfo94003* Result);
N_NIMCALL(time_t, timeinfototime_94049)(ttimeinfo94003* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_95227)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_94068)(ttimeinfo94003* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_94072)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_95265)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_95271)(NI64 t);
N_NIMCALL(time_t, fromseconds_94053)(NF since1970);
N_NIMCALL(NF, toseconds_94064)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_95824)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_95836)(NU8 m);
N_NIMCALL(void, formattoken_95848)(ttimeinfo94003* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_79285)(NimStringDesc* s, tslice79292 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_71024, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tslice79292, HEX2EHEX2E_86222)(NI a_86226, NI b_86228);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(void, insert_81001)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell41490*, usrtocell_44843)(void* usr);
static N_INLINE(void, rtladdzct_46402)(tcell41490* c);
N_NOINLINE(void, addzct_44818)(tcellseq41506* s, tcell41490* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_95999)(ttimeinfo94003* info, NimStringDesc* f);
STRING_LITERAL(TMP139, "UTC", 3);
NIM_CONST TY94650 weekdays_94649 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY94669 weekdays_94668 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP140, "", 0);
STRING_LITERAL(TMP141, "Monday", 6);
STRING_LITERAL(TMP142, "Tuesday", 7);
STRING_LITERAL(TMP143, "Wednesday", 9);
STRING_LITERAL(TMP144, "Thursday", 8);
STRING_LITERAL(TMP145, "Friday", 6);
STRING_LITERAL(TMP146, "Saturday", 8);
STRING_LITERAL(TMP147, "Sunday", 6);
NIM_CONST TY95829 lookup_95828 = {((NimStringDesc*) &TMP141),
((NimStringDesc*) &TMP142),
((NimStringDesc*) &TMP143),
((NimStringDesc*) &TMP144),
((NimStringDesc*) &TMP145),
((NimStringDesc*) &TMP146),
((NimStringDesc*) &TMP147)}
;
STRING_LITERAL(TMP148, "January", 7);
STRING_LITERAL(TMP149, "February", 8);
STRING_LITERAL(TMP150, "March", 5);
STRING_LITERAL(TMP151, "April", 5);
STRING_LITERAL(TMP152, "May", 3);
STRING_LITERAL(TMP153, "June", 4);
STRING_LITERAL(TMP154, "July", 4);
STRING_LITERAL(TMP155, "August", 6);
STRING_LITERAL(TMP156, "September", 9);
STRING_LITERAL(TMP157, "October", 7);
STRING_LITERAL(TMP158, "November", 8);
STRING_LITERAL(TMP159, "December", 8);
NIM_CONST TY95841 lookup_95840 = {((NimStringDesc*) &TMP148),
((NimStringDesc*) &TMP149),
((NimStringDesc*) &TMP150),
((NimStringDesc*) &TMP151),
((NimStringDesc*) &TMP152),
((NimStringDesc*) &TMP153),
((NimStringDesc*) &TMP154),
((NimStringDesc*) &TMP155),
((NimStringDesc*) &TMP156),
((NimStringDesc*) &TMP157),
((NimStringDesc*) &TMP158),
((NimStringDesc*) &TMP159)}
;
STRING_LITERAL(TMP160, "d", 1);
STRING_LITERAL(TMP161, "dd", 2);
STRING_LITERAL(TMP162, "ddd", 3);
STRING_LITERAL(TMP163, "dddd", 4);
STRING_LITERAL(TMP164, "h", 1);
STRING_LITERAL(TMP165, "hh", 2);
STRING_LITERAL(TMP166, "H", 1);
STRING_LITERAL(TMP167, "HH", 2);
STRING_LITERAL(TMP168, "m", 1);
STRING_LITERAL(TMP169, "mm", 2);
STRING_LITERAL(TMP170, "M", 1);
STRING_LITERAL(TMP171, "MM", 2);
STRING_LITERAL(TMP172, "MMM", 3);
STRING_LITERAL(TMP173, "MMMM", 4);
STRING_LITERAL(TMP174, "s", 1);
STRING_LITERAL(TMP175, "ss", 2);
STRING_LITERAL(TMP176, "t", 1);
STRING_LITERAL(TMP177, "tt", 2);
STRING_LITERAL(TMP178, "y", 1);
STRING_LITERAL(TMP179, "yy", 2);
STRING_LITERAL(TMP180, "yyy", 3);
STRING_LITERAL(TMP181, "yyyy", 4);
STRING_LITERAL(TMP182, "yyyyy", 5);
STRING_LITERAL(TMP183, "z", 1);
STRING_LITERAL(TMP184, "zz", 2);
STRING_LITERAL(TMP185, "zzz", 3);
STRING_LITERAL(TMP186, "ZZZ", 3);
STRING_LITERAL(TMP187, "0", 1);
STRING_LITERAL(TMP190, "PM", 2);
STRING_LITERAL(TMP191, "AM", 2);
STRING_LITERAL(TMP192, ":00", 3);
STRING_LITERAL(TMP193, "Invalid format string: ", 23);
extern TFrame* frameptr_13238;
extern TNimType NTI2409; /* TObject */
TNimType NTI94003; /* TTimeInfo */
extern TNimType NTI106; /* int */
TNimType NTI94006; /* range 0..61(int) */
TNimType NTI94009; /* range 0..59(int) */
TNimType NTI94011; /* range 0..23(int) */
TNimType NTI94014; /* range 1..31(int) */
TNimType NTI93804; /* TMonth */
TNimType NTI94018; /* range -10000..10000(int) */
TNimType NTI93806; /* TWeekDay */
TNimType NTI94024; /* range 0..365(int) */
extern TNimType NTI134; /* bool */
extern TNimType NTI143; /* string */
extern TNimType NTI18201; /* ref EInvalidValue */
extern TNimType NTI2453; /* EInvalidValue */
extern tgcheap43416 gch_43444;

N_NIMCALL(time_t, fromseconds_94057)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_94053(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < 0);
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= 0);
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == 0);
	return result;
}

N_NIMCALL(ttimeinterval94005, initinterval_94208)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	ttimeinterval94005 result;
	memset((void*)&result, 0, sizeof(result));
	result.Miliseconds = miliseconds;
	result.Seconds = seconds;
	result.Minutes = minutes;
	result.Hours = hours;
	result.Days = days;
	result.Months = months;
	result.Years = years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_94220)(NI year) {
	NIM_BOOL result;
	result = 0;
	{
		if (!(((NI) ((NI64)(year % 400))) == 0)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI64)(year % 100))) == 0)) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI64)(year % 4))) == 0)) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_94231)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_94220(year);
			if (!LOC4) goto LA5;
			result = 29;
		}
		goto LA2;
		LA5: ;
		{
			result = 28;
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = 30;
	}
	break;
	default:
	{
		result = 31;
	}
	break;
	}
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13238;
	frameptr_13238 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13238 = (*frameptr_13238).prev;
}

static N_INLINE(void, HEX2BHEX3D_94275)(NF* x_94281, NF y_94284) {
	nimfr("+=", "system.nim")
	nimln(2705, "system.nim");
	nimln(2705, "system.nim");
	(*x_94281) = ((NF)((*x_94281)) + (NF)(y_94284));
	popFrame();
}

static N_INLINE(NF, HEX2F_79238)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2566, "system.nim");
	nimln(2566, "system.nim");
	nimln(2566, "system.nim");
	nimln(2566, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_94240)(ttimeinfo94003* a, ttimeinterval94005* interval) {
	NF result;
	ttimeinfo94003 anew;
	ttimeinterval94005 newinterv;
	NU8 curmonth;
	NI mth_94270;
	NI HEX3Atmp_94396;
	NI res_94398;
	NF LOC8;
	result = 0;
	genericAssign((void*)&anew, (void*)a, (&NTI94003));
	newinterv = (*interval);
	result = 0.0;
	newinterv.Months += (NI64)((*interval).Years * 12);
	curmonth = anew.Month;
	mth_94270 = 0;
	HEX3Atmp_94396 = 0;
	HEX3Atmp_94396 = newinterv.Months;
	res_94398 = 1;
	while (1) {
		NI LOC2;
		if (!(res_94398 <= HEX3Atmp_94396)) goto LA1;
		mth_94270 = res_94398;
		LOC2 = 0;
		LOC2 = getdaysinmonth_94231(curmonth, ((NI) (anew.Year)));
		HEX2BHEX3D_94275(&result, ((NF) ((NI64)((NI64)((NI64)(LOC2 * 24) * 60) * 60))));
		{
			if (!(curmonth == ((NU8) 11))) goto LA5;
			curmonth = ((NU8) 0);
			anew.Year += 1;
		}
		goto LA3;
		LA5: ;
		{
			curmonth += 1;
		}
		LA3: ;
		res_94398 += 1;
	} LA1: ;
	HEX2BHEX3D_94275(&result, ((NF) ((NI64)((NI64)((NI64)(newinterv.Days * 24) * 60) * 60))));
	HEX2BHEX3D_94275(&result, ((NF) ((NI64)((NI64)(newinterv.Hours * 60) * 60))));
	HEX2BHEX3D_94275(&result, ((NF) ((NI64)(newinterv.Minutes * 60))));
	HEX2BHEX3D_94275(&result, ((NF) (newinterv.Seconds)));
	LOC8 = 0;
	LOC8 = HEX2F_79238(newinterv.Miliseconds, 1000);
	HEX2BHEX3D_94275(&result, LOC8);
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_94407)(ttimeinfo94003* a, ttimeinterval94005* interval, ttimeinfo94003* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_94049(a);
	t = toseconds_94064(LOC1);
	secs = toseconds_94240(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP139))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_94053(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI94003));
		(*Result).Sup.m_type = (&NTI94003);
		getgmtime_94045(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_94053(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI94003));
		(*Result).Sup.m_type = (&NTI94003);
		getlocaltime_94041(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, HEX2D_94416)(ttimeinfo94003* a, ttimeinterval94005* interval, ttimeinfo94003* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_94049(a);
	t = toseconds_94064(LOC1);
	secs = toseconds_94240(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).Tzname, ((NimStringDesc*) &TMP139))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_94053(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI94003));
		(*Result).Sup.m_type = (&NTI94003);
		getgmtime_94045(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_94053(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI94003));
		(*Result).Sup.m_type = (&NTI94003);
		getlocaltime_94041(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, gettzname_94104)(TY94106* Result) {
	unsureAsgnRef((void**) &(*Result).Field0, cstrToNimstr(tzname[(0)- 0]));
	unsureAsgnRef((void**) &(*Result).Field1, cstrToNimstr(tzname[(1)- 0]));
	goto BeforeRet;
	BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_94202)(void) {
	NI result;
	result = 0;
	result = timezone;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_94644)(struct tm* tm, NIM_BOOL local, ttimeinfo94003* Result) {
	ttimeinfo94003 LOC1;
	memset((void*)&LOC1, 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI94003);
	memset((void*)&LOC1, 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI94003);
	LOC1.Second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.Minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.Hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.Monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.Month = ((NU8) ((*tm).tm_mon));
	LOC1.Year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.Weekday = weekdays_94649[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.Yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.Isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY94106 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)&LOC10, 0, sizeof(LOC10));
			gettzname_94104(&LOC10);
			LOC1.Tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY94106 LOC12;
			memset((void*)&LOC12, 0, sizeof(LOC12));
			gettzname_94104(&LOC12);
			LOC1.Tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.Tzname = copyString(((NimStringDesc*) &TMP139));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.Timezone = gettimezone_94202();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.Timezone = 0;
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)&LOC1, (&NTI94003));
}

N_NIMCALL(struct tm, timeinfototm_94664)(ttimeinfo94003* t) {
	struct tm result;
	NI LOC1;
	memset((void*)&result, 0, sizeof(result));
	result.tm_sec = ((int) ((*t).Second));
	result.tm_min = ((int) ((*t).Minute));
	result.tm_hour = ((int) ((*t).Hour));
	result.tm_mday = ((int) ((*t).Monthday));
	result.tm_mon = ((int) ((*t).Month));
	result.tm_year = ((int) ((NI64)(((NI) ((*t).Year)) - 1900)));
	result.tm_wday = ((int) (weekdays_94668[((*t).Weekday)- 0]));
	result.tm_yday = ((int) ((*t).Yearday));
	LOC1 = 0;
	{
		if (!(*t).Isdst) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_94205)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = float64ToInt32(((NF)(((double) (LOC1))) / (NF)(((NF)(((double) (CLOCKS_PER_SEC))) / (NF)(1.0000000000000000e+03)))));
	return result;
}

N_NIMCALL(time_t, gettime_94038)(void) {
	time_t result;
	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_94041)(time_t t, ttimeinfo94003* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = localtime(&a);
	genericReset((void*)Result, (&NTI94003));
	(*Result).Sup.m_type = (&NTI94003);
	tmtotimeinfo_94644(&(*LOC1), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_94045)(time_t t, ttimeinfo94003* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime(&a);
	genericReset((void*)Result, (&NTI94003));
	(*Result).Sup.m_type = (&NTI94003);
	tmtotimeinfo_94644(&(*LOC1), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_94049)(ttimeinfo94003* timeinfo) {
	time_t result;
	ttimeinfo94003 ctimeinfo;
	struct tm LOC1;
	result = 0;
	genericAssign((void*)&ctimeinfo, (void*)timeinfo, (&NTI94003));
	LOC1 = timeinfototm_94664(&ctimeinfo);
	result = mktime(&LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_95227)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP140));
	i = 0;
	while (1) {
		NIM_BOOL LOC2;
		NIM_BOOL LOC3;
		LOC2 = 0;
		LOC3 = 0;
		LOC3 = !(((NU8)(p[i]) == (NU8)(0)));
		if (!(LOC3)) goto LA4;
		LOC3 = !(((NU8)(p[i]) == (NU8)(10)));
		LA4: ;
		LOC2 = LOC3;
		if (!(LOC2)) goto LA5;
		LOC2 = !(((NU8)(p[i]) == (NU8)(13)));
		LA5: ;
		if (!LOC2) goto LA1;
		result = addChar(result, p[i]);
		i += 1;
	} LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_94068)(ttimeinfo94003* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_94664(timeinfo);
	p = asctime(&LOC1);
	result = tostringtillnl_95227(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_94072)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime(&a);
	result = tostringtillnl_95227(LOC1);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_95265)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * 10000000) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_95271)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / 10000000)));
	return result;
}

N_NIMCALL(time_t, fromseconds_94053)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_94064)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	result = 0;
	memset((void*)&a, 0, sizeof(a));
	gettimeofday(&a, NIM_NIL);
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	ttimeinfo94003 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	LOC1 = 0;
	LOC1 = gettime_94038();
	memset((void*)&ti, 0, sizeof(ti));
	ti.Sup.m_type = (&NTI94003);
	getlocaltime_94041(LOC1, &ti);
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.Year)));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI64)(((NI) (ti.Month)) + 1))), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Monthday)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	ttimeinfo94003 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	LOC1 = 0;
	LOC1 = gettime_94038();
	memset((void*)&ti, 0, sizeof(ti));
	ti.Sup.m_type = (&NTI94003);
	getlocaltime_94041(LOC1, &ti);
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.Hour)), 2);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.Minute)), 2);
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.Second)), 2);
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_95824)(NU8 day) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_95828[(day)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_95836)(NU8 m) {
	NimStringDesc* result;
	result = 0;
	result = copyString(lookup_95840[(m)- 0]);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_79285)(NimStringDesc* s, tslice79292 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2590, "system.nim");
	nimln(2590, "system.nim");
	LOC1 = 0;
	nimln(2569, "system.nim");
	{
		nimln(2569, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP188;
		nimln(2569, "system.nim");
		nimln(2569, "system.nim");
		TMP188 = addInt(s->Sup.len, x.A);
		LOC1 = (NI64)(TMP188);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2569, "system.nim");
	{
		nimln(2569, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP189;
		nimln(2569, "system.nim");
		nimln(2569, "system.nim");
		TMP189 = addInt(s->Sup.len, x.B);
		LOC7 = (NI64)(TMP189);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(tslice79292, HEX2EHEX2E_86222)(NI a_86226, NI b_86228) {
	tslice79292 result;
	nimfr("..", "system.nim")
	memset((void*)&result, 0, sizeof(result));
	nimln(179, "system.nim");
	result.A = a_86226;
	nimln(180, "system.nim");
	result.B = b_86228;
	popFrame();
	return result;
}

static N_INLINE(tcell41490*, usrtocell_44843)(void* usr) {
	tcell41490* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell41490*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell41490))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_46402)(tcell41490* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_44818(&gch_43444.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell41490* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_44843(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell41490* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_44843((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_46402(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_95848)(ttimeinfo94003* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP140))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP169))) goto LA10;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP160))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP177))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP186))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP178))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP164))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP170))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP171))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP175))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP179))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP172))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP185))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP163))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP176))) goto LA17;
break;
	case 20: 
if (eqStrings(token, ((NimStringDesc*) &TMP182))) goto LA23;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP161))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP168))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP174))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP184))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP166))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP167))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP173))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP180))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP183))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP162))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP165))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP181))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).Monthday)) < 10)) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP187));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).Monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		tslice79292 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_95824((*info).Weekday);
		LOC41 = HEX2EHEX2E_86222(0, 2);
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_79285(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_95824((*info).Weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA49;
			LOC46 = ((NI) ((NI64)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).Hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(12 < ((NI) ((*info).Hour)))) goto LA56;
			amerhour = ((NI) ((NI64)(((NI) ((*info).Hour)) - 12)));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).Hour));
		}
		LA54: ;
		{
			if (!(amerhour < 10)) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).Hour)) < 10)) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).Hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).Minute)) < 10)) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).Minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI64)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).Month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI64)(((NI) ((*info).Month)) + 1));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		tslice79292 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_95836((*info).Month);
		LOC90 = HEX2EHEX2E_86222(0, 2);
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_79285(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_95836((*info).Month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).Second)) < 10)) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).Second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(12 <= ((NI) ((*info).Hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP190));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP191));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		tslice79292 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC115->Sup.len - 1);
		{
			if (!(fr < 0)) goto LA118;
			fr = 0;
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).Year)));
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).Year)));
		LOC122 = HEX2EHEX2E_86222(fr, (NI64)(LOC121->Sup.len - 1));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_79285(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		tslice79292 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC125->Sup.len - 2);
		{
			if (!(fr < 0)) goto LA128;
			fr = 0;
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).Year)));
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).Year)));
		LOC132 = HEX2EHEX2E_86222(fr, (NI64)(LOC131->Sup.len - 1));
		fyear = HEX5BHEX5D_79285(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!((fyear->Sup.len == 2))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar((NI64)(2 - fyear->Sup.len), 48);
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		tslice79292 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC140->Sup.len - 3);
		{
			if (!(fr < 0)) goto LA143;
			fr = 0;
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).Year)));
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).Year)));
		LOC147 = HEX2EHEX2E_86222(fr, (NI64)(LOC146->Sup.len - 1));
		fyear = HEX5BHEX5D_79285(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!((fyear->Sup.len == 3))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar((NI64)(3 - fyear->Sup.len), 48);
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		tslice79292 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC155->Sup.len - 4);
		{
			if (!(fr < 0)) goto LA158;
			fr = 0;
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).Year)));
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).Year)));
		LOC162 = HEX2EHEX2E_86222(fr, (NI64)(LOC161->Sup.len - 1));
		fyear = HEX5BHEX5D_79285(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!((fyear->Sup.len == 4))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar((NI64)(4 - fyear->Sup.len), 48);
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		tslice79292 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).Year)));
		fr = (NI64)(LOC170->Sup.len - 5);
		{
			if (!(fr < 0)) goto LA173;
			fr = 0;
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).Year)));
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).Year)));
		LOC177 = HEX2EHEX2E_86222(fr, (NI64)(LOC176->Sup.len - 1));
		fyear = HEX5BHEX5D_79285(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!((fyear->Sup.len == 5))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar((NI64)(5 - fyear->Sup.len), 48);
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI64)((NI64)((*info).Timezone / 60) / 60);
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI64)((NI64)((*info).Timezone / 60) / 60);
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((NI64)abs(hrs) < 10)) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < 0)) goto LA196;
				LOC193 = 1;
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = 0;
			}
			LA194: ;
			atindex = (NI64)((*buf)->Sup.len - (NI64)(LOC192->Sup.len - LOC193));
			insert_81001(buf, ((NimStringDesc*) &TMP187), atindex);
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI64)((NI64)((*info).Timezone / 60) / 60);
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP192));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((NI64)abs(hrs) < 10)) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP192));
			LOC208 = 0;
			{
				if (!(hrs < 0)) goto LA211;
				LOC208 = 1;
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = 0;
			}
			LA209: ;
			atindex = (NI64)((*buf)->Sup.len - (NI64)(LOC206->Sup.len - LOC208));
			insert_81001(buf, ((NimStringDesc*) &TMP187), atindex);
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).Tzname->Sup.len + 0);
appendString((*buf), (*info).Tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		einvalidvalue2453* e_95976;
		NimStringDesc* LOC217;
		e_95976 = 0;
		e_95976 = (einvalidvalue2453*) newObj((&NTI18201), sizeof(einvalidvalue2453));
		(*e_95976).Sup.Sup.Sup.m_type = (&NTI2453);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP193));
appendString(LOC217, token);
		asgnRefNoCycle((void**) &(*e_95976).Sup.Sup.message, LOC217);
		raiseException((E_Base*)e_95976, "EInvalidValue");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_95999)(ttimeinfo94003* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP140));
	i = 0;
	currentf = copyString(((NimStringDesc*) &TMP140));
	while (1) {
		switch (((NU8)(f->data[i]))) {
		case 32:
		case 45:
		case 47:
		case 58:
		case 39:
		case 0:
		case 40:
		case 41:
		case 91:
		case 93:
		case 44:
		{
			formattoken_95848(info, currentf, &result);
			currentf = copyString(((NimStringDesc*) &TMP140));
			{
				if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA9;
				i += 1;
				while (1) {
					NIM_BOOL LOC12;
					LOC12 = 0;
					LOC12 = !(((NU8)(f->data[i]) == (NU8)(39)));
					if (!(LOC12)) goto LA13;
					LOC12 = (i < (NI64)(f->Sup.len - 1));
					LA13: ;
					if (!LOC12) goto LA11;
					result = addChar(result, f->data[i]);
					i += 1;
				} LA11: ;
			}
			goto LA7;
			LA9: ;
			{
				result = addChar(result, f->data[i]);
			}
			LA7: ;
		}
		break;
		default:
		{
			{
				NIM_BOOL LOC18;
				LOC18 = 0;
				LOC18 = (currentf->Sup.len < 1);
				if (LOC18) goto LA19;
				LOC18 = ((NU8)(currentf->data[(currentf->Sup.len-1)]) == (NU8)(f->data[i]));
				LA19: ;
				if (!LOC18) goto LA20;
				currentf = addChar(currentf, f->data[i]);
			}
			goto LA16;
			LA20: ;
			{
				formattoken_95848(info, currentf, &result);
				i -= 1;
				currentf = copyString(((NimStringDesc*) &TMP140));
			}
			LA16: ;
		}
		break;
		}
		i += 1;
	} LA1: ;
	return result;
}
N_NOINLINE(void, timesInit)(void) {
}

N_NOINLINE(void, timesDatInit)(void) {
static TNimNode* TMP132[11];
static TNimNode* TMP133[12];
NI TMP135;
static char* NIM_CONST TMP134[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP136[7];
NI TMP138;
static char* NIM_CONST TMP137[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP126[33];
NTI94003.size = sizeof(ttimeinfo94003);
NTI94003.kind = 17;
NTI94003.base = (&NTI2409);
TMP132[0] = &TMP126[1];
NTI94006.size = sizeof(NI);
NTI94006.kind = 20;
NTI94006.base = (&NTI106);
NTI94006.flags = 3;
TMP126[1].kind = 1;
TMP126[1].offset = offsetof(ttimeinfo94003, Second);
TMP126[1].typ = (&NTI94006);
TMP126[1].name = "second";
TMP132[1] = &TMP126[2];
NTI94009.size = sizeof(NI);
NTI94009.kind = 20;
NTI94009.base = (&NTI106);
NTI94009.flags = 3;
TMP126[2].kind = 1;
TMP126[2].offset = offsetof(ttimeinfo94003, Minute);
TMP126[2].typ = (&NTI94009);
TMP126[2].name = "minute";
TMP132[2] = &TMP126[3];
NTI94011.size = sizeof(NI);
NTI94011.kind = 20;
NTI94011.base = (&NTI106);
NTI94011.flags = 3;
TMP126[3].kind = 1;
TMP126[3].offset = offsetof(ttimeinfo94003, Hour);
TMP126[3].typ = (&NTI94011);
TMP126[3].name = "hour";
TMP132[3] = &TMP126[4];
NTI94014.size = sizeof(NI);
NTI94014.kind = 20;
NTI94014.base = (&NTI106);
NTI94014.flags = 3;
TMP126[4].kind = 1;
TMP126[4].offset = offsetof(ttimeinfo94003, Monthday);
TMP126[4].typ = (&NTI94014);
TMP126[4].name = "monthday";
TMP132[4] = &TMP126[5];
NTI93804.size = sizeof(NU8);
NTI93804.kind = 14;
NTI93804.base = 0;
NTI93804.flags = 3;
for (TMP135 = 0; TMP135 < 12; TMP135++) {
TMP126[TMP135+6].kind = 1;
TMP126[TMP135+6].offset = TMP135;
TMP126[TMP135+6].name = TMP134[TMP135];
TMP133[TMP135] = &TMP126[TMP135+6];
}
TMP126[18].len = 12; TMP126[18].kind = 2; TMP126[18].sons = &TMP133[0];
NTI93804.node = &TMP126[18];
TMP126[5].kind = 1;
TMP126[5].offset = offsetof(ttimeinfo94003, Month);
TMP126[5].typ = (&NTI93804);
TMP126[5].name = "month";
TMP132[5] = &TMP126[19];
NTI94018.size = sizeof(NI);
NTI94018.kind = 20;
NTI94018.base = (&NTI106);
NTI94018.flags = 3;
TMP126[19].kind = 1;
TMP126[19].offset = offsetof(ttimeinfo94003, Year);
TMP126[19].typ = (&NTI94018);
TMP126[19].name = "year";
TMP132[6] = &TMP126[20];
NTI93806.size = sizeof(NU8);
NTI93806.kind = 14;
NTI93806.base = 0;
NTI93806.flags = 3;
for (TMP138 = 0; TMP138 < 7; TMP138++) {
TMP126[TMP138+21].kind = 1;
TMP126[TMP138+21].offset = TMP138;
TMP126[TMP138+21].name = TMP137[TMP138];
TMP136[TMP138] = &TMP126[TMP138+21];
}
TMP126[28].len = 7; TMP126[28].kind = 2; TMP126[28].sons = &TMP136[0];
NTI93806.node = &TMP126[28];
TMP126[20].kind = 1;
TMP126[20].offset = offsetof(ttimeinfo94003, Weekday);
TMP126[20].typ = (&NTI93806);
TMP126[20].name = "weekday";
TMP132[7] = &TMP126[29];
NTI94024.size = sizeof(NI);
NTI94024.kind = 20;
NTI94024.base = (&NTI106);
NTI94024.flags = 3;
TMP126[29].kind = 1;
TMP126[29].offset = offsetof(ttimeinfo94003, Yearday);
TMP126[29].typ = (&NTI94024);
TMP126[29].name = "yearday";
TMP132[8] = &TMP126[30];
TMP126[30].kind = 1;
TMP126[30].offset = offsetof(ttimeinfo94003, Isdst);
TMP126[30].typ = (&NTI134);
TMP126[30].name = "isDST";
TMP132[9] = &TMP126[31];
TMP126[31].kind = 1;
TMP126[31].offset = offsetof(ttimeinfo94003, Tzname);
TMP126[31].typ = (&NTI143);
TMP126[31].name = "tzname";
TMP132[10] = &TMP126[32];
TMP126[32].kind = 1;
TMP126[32].offset = offsetof(ttimeinfo94003, Timezone);
TMP126[32].typ = (&NTI106);
TMP126[32].name = "timezone";
TMP126[0].len = 11; TMP126[0].kind = 2; TMP126[0].sons = &TMP132[0];
NTI94003.node = &TMP126[0];
}

